// PCI Academy courses (§6.1–6.2). Courses reuse canonical Library content
// rather than duplicate it: each lesson's reading is a framework article.
// Structure per lesson: Module → (Video, when one exists) → Reading →
// Observation → Journal → Optional PCI Analysis.
//
// "PCI Foundations" is DERIVED course material assembled for this build from
// the canonical framework. Its short orientations and exercises need review
// by the canon owner. No lesson has video yet, so no player is shown.
// "The Art of Being — Foundations" stays in draft until its lessons and video
// are designed; the chapters themselves are published in the Library.
import type { Course } from '@/lib/content/types'

export const COURSES: Course[] = [
  {
    slug: 'pci-foundations',
    title: 'PCI Foundations: The Seven Operations',
    summary:
      'A guided route through the seven principles / operations, the STOP boundary and the epistemic classes, using the canonical PCI framework texts. Each lesson ends with an observation and a journal subject; analysis is optional.',
    canon_status: 'derived',
    status: 'published',
    modules: [
      { slug: 'orientation', title: 'Orientation' },
      { slug: 'separating', title: 'Separating the material' },
      { slug: 'relating', title: 'Relating the material' },
      { slug: 'reporting', title: 'Reporting and stopping' },
    ],
    lessons: [
      {
        lesson_id: 'the-boundary',
        module: 'orientation',
        title: 'Visibility, and where it stops',
        orientation: 'PCI makes structure visible and then stops. This lesson reads the product definition and the processing boundary side by side.',
        related_chapters: [],
        related_concepts: ['pci', 'visibility', 'stop-boundary'],
        reading: [{ slug: 'what-pci-is' }, { slug: 'processing-boundary' }],
        observation: 'Recall one piece of advice you received recently. Separate what the adviser observed from what they told you to do.',
        journal_prompt: 'Where today did an observation of yours turn, within a sentence, into an instruction?',
        optional_observation: true,
        resources: [],
      },
      {
        lesson_id: 'input',
        module: 'separating',
        title: 'Input: before explanation',
        orientation: 'The first operation preserves the raw material before explanation. The record of what occurred is kept apart from what it is taken to mean.',
        related_chapters: [],
        related_concepts: ['input', 'structured-observation-record'],
        reading: [{ slug: 'seven-operations' }, { slug: 'structured-observation-records' }],
        observation: 'Write three sentences about a recent event using only what a recording would have captured.',
        journal_prompt: 'What happened today that you are already explaining to yourself? Write only what occurred, before any explanation.',
        optional_observation: true,
        resources: [],
      },
      {
        lesson_id: 'decomposition',
        module: 'separating',
        title: 'Decomposition: one narrative, many parts',
        orientation: 'Event, behavior, interpretation, emotion, judgment, assumption, context, identity attribution and unknown are commonly experienced as a single narrative. Decomposition separates them.',
        related_chapters: [],
        related_concepts: ['decomposition', 'interpretation', 'identity-attribution'],
        reading: [{ slug: 'structured-observation-records' }],
        observation: 'Take one sentence you wrote in the previous lesson and label each part of it with a decomposition category.',
        journal_prompt: 'In one situation from today, which part was the event, and which part was the meaning you gave it?',
        optional_observation: true,
        resources: [],
      },
      {
        lesson_id: 'evidentiary-separation',
        module: 'separating',
        title: 'Evidentiary Separation',
        orientation: 'What is evidenced, reported, inferred, interpreted, symbolic, philosophical, speculative, or unknown — and how strongly it is supported.',
        related_chapters: [],
        related_concepts: ['epistemic-class', 'confidence-calibration'],
        reading: [{ slug: 'epistemic-classes' }, { slug: 'constitutional-invariants' }],
        observation: 'List one statement about yourself you consider true. Mark its epistemic class and the support you have for it.',
        journal_prompt: 'What do you know happened today, and what do you believe happened?',
        optional_observation: true,
        resources: [],
      },
      {
        lesson_id: 'contextual-comparison',
        module: 'relating',
        title: 'Contextual Comparison',
        orientation: 'Similar events are not structurally equivalent until their context is compared. Comparison is not causation.',
        related_chapters: [],
        related_concepts: ['contextual-comparison', 'context-differential', 'temporal-intelligence'],
        reading: [{ slug: 'time-and-context' }],
        observation: 'Pick two occasions that felt alike. List what was constant and what changed between them.',
        journal_prompt: 'Where has something structurally similar to today’s main event appeared before? What was different about the context then?',
        optional_observation: true,
        resources: [],
      },
      {
        lesson_id: 'pattern-detection',
        module: 'relating',
        title: 'Pattern Detection and Pattern Adoption',
        orientation: 'Recurrence is reported without converting it into identity, and without inferring its origin.',
        related_chapters: [],
        related_concepts: ['pattern-detection', 'pattern-adoption'],
        reading: [{ slug: 'pattern-adoption' }],
        observation: 'Name one thing you describe with “always”. Count the instances you can actually date.',
        journal_prompt: 'What appeared to repeat today, and under what conditions did it appear?',
        optional_observation: true,
        resources: [],
      },
      {
        lesson_id: 'contradiction-detection',
        module: 'relating',
        title: 'Contradiction Detection',
        orientation: 'Contradiction exposes tension without forcing one side to be false. Subject, meaning, scope, time, context and observer position are compared before anything is labelled.',
        related_chapters: [],
        related_concepts: ['contradiction', 'contradiction-detection'],
        reading: [{ slug: 'contradiction-engine' }, { slug: 'observer-observed' }],
        observation: 'Find two statements of yours that seem to conflict. Compare them on time and context before calling them a contradiction.',
        journal_prompt: 'Where today did what you said and what you did point in different directions?',
        optional_observation: true,
        resources: [],
      },
      {
        lesson_id: 'observational-report',
        module: 'reporting',
        title: 'The Observational Report',
        orientation: 'After separating the material, what can be observed without deciding what to think, become, choose or do. The report returns visibility and stops.',
        related_chapters: [],
        related_concepts: ['observational-report', 'meta-observational-integrity-audit'],
        reading: [{ slug: 'integrity-audit-and-report' }],
        observation: 'Write a five-line report on this week that contains no instruction to yourself.',
        journal_prompt: 'After separating today’s material, what can simply be observed, without deciding what to do about it?',
        optional_observation: true,
        resources: [],
      },
    ],
  },
  {
    slug: 'art-of-being-foundations',
    title: 'The Art of Being — Foundations',
    summary: 'Module → Short Video → Reading → Observation → Journal → Optional PCI Analysis, built on The Art of Being. The chapters are published in the Library; the course awaits its lesson design and video material.',
    canon_status: 'provisional',
    status: 'draft',
    modules: [],
    lessons: [],
  },
]
