// Daily Journal prompt bank (§3.3, §14): one observational subject per day,
// each mapped to a PCI concept.
//
// Prompt 1 is the blueprint's own example and is canonical. The other 89 are
// drafted for this build and are PROVISIONAL: they need review and explicit
// approval by the PCI canon owner before promotion (§1.4). Every prompt is
// checked by the constitutional validator in the test suite.
import type { JournalPrompt } from '@/lib/content/types'

const P: [string, string][] = [
  ['input', 'Out of the decisions you made today, which appeared to originate from the immediate situation, and which appeared to reproduce something familiar?'],
  ['input', 'What happened today that you are already explaining to yourself? Write only what occurred, before any explanation.'],
  ['input', 'Which moment today would a camera in the room have recorded differently from the way you remember it?'],
  ['input', 'What was said today, word for word, that stayed with you?'],
  ['input', 'Which event today arrived already labelled, as good or bad, before you had described it?'],
  ['input', 'What material is present for you today that has no event attached to it — a mood, an image, a thought?'],
  ['input', 'Describe one ordinary moment from today in as much plain detail as you can recall.'],
  ['input', 'What did you notice first when you woke, before the day had a story?'],
  ['decomposition', 'In one situation from today, which part was the event, and which part was the meaning you gave it?'],
  ['decomposition', 'Which emotion appeared today, and what was it attached to when it appeared?'],
  ['decomposition', 'What judgment did you make today — of a person, a task or yourself — and what was it judged against?'],
  ['decomposition', 'What did you assume today without checking it?'],
  ['decomposition', 'What did you expect to happen today that did not, and where did that expectation come from in the moment?'],
  ['decomposition', 'Where today did “I did this” become “I am this”?'],
  ['decomposition', 'Which conditions today — tiredness, place, company, time — might have changed how something looked?'],
  ['decomposition', 'In a moment of friction today, what remains unknown to you about the other person’s side?'],
  ['decomposition', 'What did you do today, and what did you not do, in one situation that mattered to you?'],
  ['decomposition', 'Which feeling today described someone else’s conduct — “ignored”, “judged”, “let down” — rather than your own state?'],
  ['decomposition', 'Take one sentence you said or thought today. Which words in it are description, and which are evaluation?'],
  ['decomposition', 'What role were you in today (parent, colleague, friend, stranger), and how did the role shape what you saw?'],
  ['contextual_comparison', 'Where has something structurally similar to today’s main event appeared before? What was different about the context then?'],
  ['contextual_comparison', 'What looked the same today as a previous time, yet took place under different conditions?'],
  ['contextual_comparison', 'Which of today’s reactions would have been different in another room, with other people, or at another hour?'],
  ['contextual_comparison', 'What stayed constant today across two quite different situations?'],
  ['contextual_comparison', 'Compare a morning moment with an evening moment from today. What changed besides the time?'],
  ['contextual_comparison', 'When did you last feel what you felt today? What was present then that is absent now?'],
  ['contextual_comparison', 'Which comparison did you make today between yourself and someone else, and what did the comparison leave out?'],
  ['contextual_comparison', 'What would today’s event look like if it had happened ten years ago?'],
  ['pattern_detection', 'What appeared to repeat today, and under what conditions did it appear?'],
  ['pattern_detection', 'Which thought returned more than once today? What was happening each time it returned?'],
  ['pattern_detection', 'What do you describe with the word “always”? How many actual instances can you list?'],
  ['pattern_detection', 'Which response of yours seemed to arrive before you chose it today?'],
  ['pattern_detection', 'What repeated today in how others responded to you, and what was similar in how you approached them?'],
  ['pattern_detection', 'What did not repeat today that usually does? What was different?'],
  ['pattern_detection', 'Which small habit ran today without your attention? When did it become visible?'],
  ['pattern_detection', 'What is the most recent time something you call “a pattern” did not happen?'],
  ['contradiction_detection', 'Where today did what you said and what you did point in different directions?'],
  ['contradiction_detection', 'What do you believe about yourself that today’s events did not match?'],
  ['contradiction_detection', 'What two things did you want today that could not both happen?'],
  ['contradiction_detection', 'Which opinion of yours shifted today, even slightly? What was the earlier version?'],
  ['contradiction_detection', 'Where did you say “I don’t mind” today while something in you did mind?'],
  ['contradiction_detection', 'What value did you hold today that was hard to act on? What happened instead?'],
  ['contradiction_detection', 'Which two accounts of the same event — yours and someone else’s — do not fit together?'],
  ['contradiction_detection', 'What tension from today remains unresolved, and what does it look like when left unresolved?'],
  ['evidentiary_separation', 'What do you know happened today, and what do you believe happened?'],
  ['evidentiary_separation', 'Which conclusion from today rests on one moment alone?'],
  ['evidentiary_separation', 'What did you infer about someone’s intention today? What did they actually say or do?'],
  ['evidentiary_separation', 'What remains unknown about today’s main event, and how do you carry the unknown?'],
  ['evidentiary_separation', 'Which image or symbol stayed with you today? What is it, and what have you made it mean?'],
  ['evidentiary_separation', 'Which of today’s thoughts was a hypothesis that felt like a fact?'],
  ['evidentiary_separation', 'What did you report to yourself today about how you felt, and what else could the sensation have been?'],
  ['evidentiary_separation', 'If you had to mark today’s account with “seen”, “heard”, “felt” and “concluded”, where would each mark go?'],
  ['observational_report', 'After separating today’s material, what can simply be observed, without deciding what to do about it?'],
  ['observational_report', 'What became visible today that was not visible yesterday?'],
  ['observational_report', 'Describe today in five plain observations, none of which contains an instruction.'],
  ['observational_report', 'What is present in today’s material that does not need resolving tonight?'],
  ['observational_report', 'What would an account of today look like if it ended at observation?'],
  ['observer_observed', 'What did you notice yourself noticing today?'],
  ['observer_observed', 'Where was your attention today, and what did it pass over?'],
  ['observer_observed', 'What frame were you looking through when today’s strongest moment happened?'],
  ['observer_observed', 'How did your state — rested, hurried, hungry, calm — shape what you perceived today?'],
  ['observer_observed', 'When did you watch yourself today as if from the outside? What did you see?'],
  ['observer_observed', 'Which of today’s judgments says more about the one judging than the one judged?'],
  ['observer_observed', 'What meaning did you assign today within a second of seeing something?'],
  ['observer_observed', 'What happened to an observation today once you became part of it?'],
  ['pattern_adoption', 'Which way of responding did you use today that you remember first using long ago?'],
  ['pattern_adoption', 'What habit of thought was reinforced today, and by what?'],
  ['pattern_adoption', 'What do you do by default in conflict? When did the default run today?'],
  ['pattern_adoption', 'Which pattern have you begun to call part of who you are? When is it absent?'],
  ['pattern_adoption', 'What pattern became visible to you today while it was happening?'],
  ['pattern_adoption', 'What pattern has changed in you over the last year, and under what conditions does the older version still appear?'],
  ['on_the_contrary', 'What went wrong today? What expectation made it wrong?'],
  ['on_the_contrary', 'Which problem from today would look different from another position within the same situation?'],
  ['on_the_contrary', 'What variables were missing from your view of today’s unwanted event?'],
  ['on_the_contrary', 'Within what larger system did today’s difficulty take place? Who and what else was part of it?'],
  ['on_the_contrary', 'What did today’s imbalance make visible about the relationship between the parts?'],
  ['on_the_contrary', 'What is the contrary position to your strongest reaction today, stated as its holder would state it?'],
  ['repetition', 'What did you repeat today that was not quite the same as last time? What had changed — in you, the context, or the act?'],
  ['repetition', 'Which practice did you do today? What did the repetition feel like this time?'],
  ['repetition', 'Where did you expect today to be a copy of yesterday, and where was it not?'],
  ['neutrality', 'Was there a moment today with no strong reaction? What was present in it?'],
  ['neutrality', 'What subtle thing did you perceive today that a louder moment would have covered?'],
  ['neutrality', 'Which event today did you manage to see before deciding how you felt about it?'],
  ['emotion', 'Which emotion today carried information? What was it pointing at?'],
  ['emotion', 'Which emotion did you have today without it having you?'],
  ['emotion', 'Which feeling today did you call a problem? What was it before it was called that?'],
  ['identity', 'Which version of yourself appeared today that you do not usually include in your self-description?'],
  ['identity', 'What possibility showed up in you today that does not fit the identity you usually hold?'],
  ['choice', 'Where today did a choice happen without being noticed as a choice?'],
  ['choice', 'Which choice from today is still open, and what does it look like from here?'],
]

export const JOURNAL_PROMPTS: JournalPrompt[] = P.map(([concept, text], i) => ({
  id: `JP-${String(i + 1).padStart(3, '0')}`,
  ord: i + 1,
  text,
  concept,
  canon_status: i === 0 ? 'canonical' : 'provisional',
  status: 'approved',
}))

export const PROMPT_CONCEPT_LABELS: Record<string, string> = {
  input: 'Input',
  decomposition: 'Decomposition',
  contextual_comparison: 'Contextual Comparison',
  pattern_detection: 'Pattern Detection',
  contradiction_detection: 'Contradiction Detection',
  evidentiary_separation: 'Evidentiary Separation',
  observational_report: 'Observational Report',
  observer_observed: 'Observer / Observed',
  pattern_adoption: 'Pattern Adoption',
  on_the_contrary: 'On the Contrary',
  repetition: 'Repetition',
  neutrality: 'Neutrality and Subtlety',
  emotion: 'Emotion as Information',
  identity: 'Identity as a Field of Possibilities',
  choice: 'Choice',
}

/** One subject per day, deterministic by calendar date. */
export function promptForDate(date: string): JournalPrompt {
  const d = new Date(`${date}T12:00:00Z`)
  const start = Date.UTC(2026, 0, 1)
  const day = Math.floor((d.getTime() - start) / 86400000)
  const i = ((day % JOURNAL_PROMPTS.length) + JOURNAL_PROMPTS.length) % JOURNAL_PROMPTS.length
  return JOURNAL_PROMPTS[i]
}
