// Generates supabase/seed.sql from the canonical seeds in content/seeds.
// Idempotent: safe to apply repeatedly (supabase db reset applies it).
// Published items pass through the database's own publication validation;
// Art of Being chapters and companion articles come from the author's
// manuscript; unsupplied front and back matter is registered as drafts with no
// version, so it cannot publish until text is entered through the CMS.
import { writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { ART_OF_BEING, COMPANION } from '../content/seeds/art-of-being.ts'
import { COURSES } from '../content/seeds/courses.ts'
import { FRAMEWORK } from '../content/seeds/framework.ts'
import { GLOSSARY } from '../content/seeds/glossary.ts'
import { JOURNAL_PROMPTS } from '../content/seeds/journal-prompts.ts'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const q = (s: string | null | undefined) => (s === null || s === undefined ? 'null' : `$pci$${s}$pci$`)
const arr = (xs: string[]) => `array[${xs.map(q).join(', ')}]::text[]`
const out: string[] = ['-- GENERATED by scripts/db-seed.mts — do not edit. Regenerate with: pnpm db:seed', 'begin;', '']

for (const c of [...FRAMEWORK, ...ART_OF_BEING, ...COMPANION]) {
  const complete = c.status === 'published'
  out.push(
    `insert into public.content_items (slug, type, collection, title, summary, canon_status, status, chapter_order, current_version)
values (${q(c.slug)}, ${q(c.type)}, ${q(c.collection)}, ${q(c.title)}, ${q(c.summary)}, ${q(c.canon_status)}, ${q(complete ? 'approved' : 'draft')}, ${c.order ?? 'null'}, ${complete ? c.content_version : 'null'})
on conflict (slug) do nothing;`,
  )
  if (complete) {
    out.push(
      `insert into public.content_versions (content_id, content_version, title, body, canon_status, canon_version, status, change_note)
select id, ${c.content_version}, ${q(c.title)}, ${q(c.body)}, ${q(c.canon_status)}, ${q(c.canon_version)}, 'published', ${q(`Seeded from ${c.source ?? 'canon'}`)} from public.content_items where slug = ${q(c.slug)}
on conflict (content_id, content_version) do nothing;`,
      `update public.content_items set status = 'published' where slug = ${q(c.slug)} and status = 'approved';`,
    )
  }
  out.push('')
}

for (const g of GLOSSARY) {
  out.push(`insert into public.glossary_terms (slug, term, definition, canon_status, status) values (${q(g.slug)}, ${q(g.term)}, ${q(g.definition)}, ${q(g.canon_status)}, 'published') on conflict (slug) do nothing;`)
}
out.push('')
for (const p of JOURNAL_PROMPTS) {
  out.push(`insert into public.journal_prompts (id, ord, text, concept, canon_status, status) values (${q(p.id)}, ${p.ord}, ${q(p.text)}, ${q(p.concept)}, ${q(p.canon_status)}, ${q(p.status)}) on conflict (id) do nothing;`)
}
out.push('')
for (const c of COURSES) {
  out.push(`insert into public.courses (slug, title, summary, canon_status, status) values (${q(c.slug)}, ${q(c.title)}, ${q(c.summary)}, ${q(c.canon_status)}, ${q(c.status)}) on conflict (slug) do nothing;`)
  c.modules.forEach((m, i) => out.push(`insert into public.course_modules (course_slug, slug, title, ord) values (${q(c.slug)}, ${q(m.slug)}, ${q(m.title)}, ${i + 1}) on conflict do nothing;`))
  c.lessons.forEach((l, i) =>
    out.push(
      `insert into public.lessons (course_slug, lesson_id, module_slug, ord, title, video_url, transcript, related_chapters, related_concepts, journal_prompt, optional_observation, resources)
values (${q(c.slug)}, ${q(l.lesson_id)}, ${q(l.module)}, ${i + 1}, ${q(l.title)}, ${q(l.video?.url)}, ${q(l.video?.transcript)}, ${arr(l.related_chapters)}, ${arr(l.related_concepts)}, ${q(l.journal_prompt)}, ${l.optional_observation}, ${q(JSON.stringify(l.resources))}::jsonb)
on conflict do nothing;`,
    ),
  )
  out.push('')
}
out.push('commit;', '')
writeFileSync(join(root, 'supabase', 'seed.sql'), out.join('\n'))
console.log(`supabase/seed.sql: ${FRAMEWORK.length} framework texts, ${ART_OF_BEING.length} Art of Being entries, ${COMPANION.length} companion articles, ${GLOSSARY.length} terms, ${JOURNAL_PROMPTS.length} prompts, ${COURSES.length} courses.`)
