// Generates supabase/seed.sql from the canonical seeds in content/seeds.
// Idempotent: safe to apply repeatedly (supabase db reset applies it).
// Published items pass through the database's own publication validation;
// Art of Being chapters, companion articles and Library sub-chapters come from
// the author's manuscript; the blueprint framework texts and the unsupplied
// front and back matter are registered as drafts with no version, so they
// cannot publish until text is entered through the CMS.
import { writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { ART_OF_BEING, COMPANION, LIBRARY } from '../content/seeds/art-of-being.ts'
import { FRAMEWORK } from '../content/seeds/framework.ts'
import { GLOSSARY } from '../content/seeds/glossary.ts'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const q = (s: string | null | undefined) => (s === null || s === undefined ? 'null' : `$pci$${s}$pci$`)
const out: string[] = ['-- GENERATED by scripts/db-seed.mts — do not edit. Regenerate with: pnpm db:seed', 'begin;', '']

for (const c of [...FRAMEWORK, ...ART_OF_BEING, ...COMPANION, ...LIBRARY]) {
  const complete = c.status === 'published'
  out.push(
    `insert into public.content_items (slug, type, collection, title, summary, canon_status, status, chapter_order, current_version)
values (${q(c.slug)}, ${q(c.type)}, ${q(c.collection)}, ${q(c.title)}, ${q(c.summary)}, ${q(c.canon_status)}, ${q(complete ? 'approved' : 'draft')}, ${c.order ?? 'null'}, ${complete ? c.content_version : 'null'})
on conflict (slug) do nothing;`,
  )
  if (complete) {
    out.push(
      `insert into public.content_versions (content_id, content_version, title, body, canon_status, canon_version, status, change_note)
select id, ${c.content_version}, ${q(c.title)}, ${q(c.body)}, ${q(c.canon_status)}, ${q(c.canon_version)}, 'published', ${q(`Seeded from ${c.source ?? 'canon'}`)} from public.content_items where slug = ${q(c.slug)}
on conflict (content_id, content_version) do nothing;`,
      `update public.content_items set status = 'published' where slug = ${q(c.slug)} and status = 'approved';`,
    )
  }
  out.push('')
}

for (const g of GLOSSARY) {
  out.push(`insert into public.glossary_terms (slug, term, definition, canon_status, status) values (${q(g.slug)}, ${q(g.term)}, ${q(g.definition)}, ${q(g.canon_status)}, 'published') on conflict (slug) do nothing;`)
}
out.push('commit;', '')
writeFileSync(join(root, 'supabase', 'seed.sql'), out.join('\n'))
console.log(`supabase/seed.sql: ${FRAMEWORK.length} framework texts (drafts), ${ART_OF_BEING.length} Art of Being entries, ${COMPANION.length} companion articles, ${LIBRARY.length} library sub-chapters, ${GLOSSARY.length} terms.`)
