// Generates content/seeds/manuscript.generated.ts from the author's manuscript
// files in content/manuscript/. The markdown files are the source of truth;
// edit them, then run: pnpm content:sync  (CI checks the two agree).
//
// Each file carries front matter (collection, chapter or order, title, canon).
// The H1 repeats the title and is dropped; an italic line directly under it is
// the subtitle, shown as the reader's lede. The body is otherwise verbatim.
import { readdirSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

export interface ManuscriptText {
  file: string
  order: number
  title: string
  subtitle: string
  canon: string
  content_type: string
  body: string
}

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const dir = (name: string) => join(root, 'content', 'manuscript', name)
const OUT = join(root, 'content', 'seeds', 'manuscript.generated.ts')

export function parseManuscript(file: string, src: string): ManuscriptText {
  const m = /^---\n([\s\S]*?)\n---\n/.exec(src.replace(/\r\n/g, '\n'))
  if (!m) throw new Error(`${file}: missing front matter`)
  const meta: Record<string, string> = {}
  for (const line of m[1].split('\n')) {
    const kv = /^(\w+):\s*"?(.*?)"?\s*$/.exec(line)
    if (kv) meta[kv[1]] = kv[2]
  }
  const order = Number(meta.chapter ?? meta.order)
  if (!meta.title || !Number.isInteger(order)) throw new Error(`${file}: front matter needs a title and a chapter/order number`)
  const lines = src.replace(/\r\n/g, '\n').slice(m[0].length).split('\n')
  while (lines.length && !lines[0].trim()) lines.shift()
  if (lines[0]?.startsWith('# ')) lines.shift()
  while (lines.length && !lines[0].trim()) lines.shift()
  let subtitle = ''
  const sub = /^\*([^*]+)\*$/.exec(lines[0]?.trim() ?? '')
  if (sub) {
    subtitle = sub[1].trim()
    lines.shift()
  }
  return { file, order, title: meta.title, subtitle, canon: meta.canon ?? '', content_type: meta.content_type ?? '', body: lines.join('\n').trim() }
}

function readCollection(name: string): ManuscriptText[] {
  return readdirSync(dir(name))
    .filter((f) => f.endsWith('.md'))
    .sort()
    .map((f) => parseManuscript(`content/manuscript/${name}/${f}`, readFileSync(join(dir(name), f), 'utf8')))
    .sort((a, b) => a.order - b.order)
}

export function render(): string {
  const book = readCollection('art-of-being')
  const companion = readCollection('companion')
  return [
    '// GENERATED by scripts/manuscript.mts from content/manuscript/ — do not edit.',
    '// Regenerate with: pnpm content:sync',
    '',
    'export interface ManuscriptText {',
    '  file: string',
    '  order: number',
    '  title: string',
    '  subtitle: string',
    '  canon: string',
    '  content_type: string',
    '  body: string',
    '}',
    '',
    `export const BOOK_CHAPTERS: ManuscriptText[] = ${JSON.stringify(book, null, 2)}`,
    '',
    `export const COMPANION_ARTICLES: ManuscriptText[] = ${JSON.stringify(companion, null, 2)}`,
    '',
  ].join('\n')
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  const next = render()
  if (process.argv.includes('--check')) {
    let current = ''
    try {
      current = readFileSync(OUT, 'utf8')
    } catch {}
    if (current !== next) {
      console.error('content/seeds/manuscript.generated.ts is out of date. Run: pnpm content:sync')
      process.exit(1)
    }
    console.log('Manuscript seeds are up to date.')
  } else {
    writeFileSync(OUT, next)
    console.log('content/seeds/manuscript.generated.ts written.')
  }
}
