-- GENERATED by scripts/db-seed.mts — do not edit. Regenerate with: pnpm db:seed
begin;

insert into public.content_items (slug, type, collection, title, summary, canon_status, status, chapter_order, current_version)
values ($pci$what-pci-is$pci$, $pci$framework$pci$, $pci$pci-framework$pci$, $pci$What PCI Is — and What It Is Not$pci$, $pci$PCI may make structure visible. It may not convert visibility into behavioral obligation.$pci$, $pci$canonical$pci$, $pci$approved$pci$, 1, 1)
on conflict (slug) do nothing;
insert into public.content_versions (content_id, content_version, title, body, canon_status, canon_version, status, change_note)
select id, 1, $pci$What PCI Is — and What It Is Not$pci$, $pci$The PCI Web App is an observational intelligence environment built around [[Psycho-Creative Intelligence|pci]]. It is not a motivational system, personality test, diagnosis engine, therapy application, or automated advice platform.

Its function is to receive human material, separate the components of that material, compare it across context and time where evidence permits, distinguish evidence from interpretation, surface patterns and contradictions, and produce an [[observational report]].

```
Input -> Decomposition -> Contextual Comparison -> Pattern Detection -> Contradiction Detection -> Evidentiary Separation -> Observational Report -> STOP
```

## The central contract

The central product contract is simple: PCI may make structure visible. It may not convert visibility into behavioral obligation.

> Visibility is the output. Human choice begins outside the PCI Engine.

## What PCI is not

- A diagnosis engine
- A therapy substitute
- A motivational application
- A personality scoring system
- A behavior-correction platform
- A moral ranking system
- A system that claims access to a permanent or hidden true self
- An engine that automatically decides what a user should do next

## The processing boundary

Any choice, action, strategy, intervention, recommendation, or behavioral direction that follows an observational report belongs outside the PCI Engine and requires a separate non-PCI task or service context.

## The system as a whole

PCI Academy provides the corpus. The user provides material. The PCI Engine exposes structure. The epistemic layer protects the distinction between evidence and interpretation. The documentation layer preserves material over time. The relational layer reveals connections without manufacturing identity claims. The Academy layer provides guided access to the corpus. Infrastructure provides security, persistence, access and scale.

PCI stops. Human choice begins outside the engine.$pci$, $pci$canonical$pci$, $pci$2026.09.25$pci$, 'published', $pci$Seeded from Blueprint §Executive Summary, §1.1–1.3, Final System Definition$pci$ from public.content_items where slug = $pci$what-pci-is$pci$
on conflict (content_id, content_version) do nothing;
update public.content_items set status = 'published' where slug = $pci$what-pci-is$pci$ and status = 'approved';

insert into public.content_items (slug, type, collection, title, summary, canon_status, status, chapter_order, current_version)
values ($pci$seven-operations$pci$, $pci$framework$pci$, $pci$pci-framework$pci$, $pci$The Seven Principles / Operations$pci$, $pci$Seven user-facing questions form the interaction layer of PCI. They replace the earlier twelve-question architecture.$pci$, $pci$canonical$pci$, $pci$approved$pci$, 2, 1)
on conflict (slug) do nothing;
insert into public.content_versions (content_id, content_version, title, body, canon_status, canon_version, status, change_note)
select id, 1, $pci$The Seven Principles / Operations$pci$, $pci$The current product replaces the older twelve-question architecture with seven user-facing principles / operations. These seven questions are the interaction layer; they do not limit the internal intelligence available to the mature PCI engine.

## 1 — Input

**What actually occurred, or what material is present, before I explain what it means?**

Preserve the raw material before explanation.

## 2 — Decomposition

**What parts of this are event, behavior, interpretation, emotion, judgment, assumption, context, identity attribution, and unknown?**

Separate categories that are commonly experienced as a single narrative.

## 3 — Contextual Comparison

**Where has something structurally similar appeared before, and what was the same or different about the context?**

Compare without treating similarity as causation or sameness.

## 4 — Pattern Detection

**What appears to repeat across the available material, and under what conditions does that repetition appear?**

Report recurrence without converting it into identity.

## 5 — Contradiction Detection

**What parts of the available material appear inconsistent, incompatible, revised, or unresolved when compared with one another?**

Expose tension without forcing resolution.

## 6 — Evidentiary Separation

**What is directly evidenced here, what is interpreted or inferred, what remains hypothetical or symbolic, and what is presently unknown?**

Protect epistemic classes.

## 7 — Observational Report

**After separating all of this material, what can actually be observed without deciding what I should think, become, choose, or do?**

Return visibility and stop.

## Guided and direct use

In Observe, the seven questions can be answered one at a time (Guided Mode), or a single submission can be processed into the structured PCI report (Direct Analysis Mode). In both, all seven operations are represented in the result.$pci$, $pci$canonical$pci$, $pci$2026.09.25$pci$, 'published', $pci$Seeded from Blueprint §2$pci$ from public.content_items where slug = $pci$seven-operations$pci$
on conflict (content_id, content_version) do nothing;
update public.content_items set status = 'published' where slug = $pci$seven-operations$pci$ and status = 'approved';

insert into public.content_items (slug, type, collection, title, summary, canon_status, status, chapter_order, current_version)
values ($pci$processing-boundary$pci$, $pci$framework$pci$, $pci$pci-framework$pci$, $pci$The Canonical Processing Boundary$pci$, $pci$Behind the seven questions sits the internal PCI v1.1 processing order. It ends at the observational report, and stops.$pci$, $pci$canonical$pci$, $pci$approved$pci$, 3, 1)
on conflict (slug) do nothing;
insert into public.content_versions (content_id, content_version, title, body, canon_status, canon_version, status, change_note)
select id, 1, $pci$The Canonical Processing Boundary$pci$, $pci$```
INPUT -> DECOMPOSITION -> CONTEXTUAL COMPARISON -> PATTERN DETECTION -> CONTRADICTION DETECTION -> EVIDENTIARY SEPARATION -> OBSERVATIONAL REPORT -> STOP
```

Any choice, action, strategy, intervention, recommendation, or behavioral direction that follows belongs outside the PCI Engine and requires a separate non-PCI task or service context.

## The internal processing order

Behind the seven-question interface, the internal engine may run the mature observational architecture when sufficient material exists:

```
INTAKE
-> STRUCTURED OBSERVATION RECORDS
-> DECOMPOSITION
-> TEMPORAL INTELLIGENCE
-> CONTEXT DIFFERENTIAL
-> CONTRADICTION ENGINE
-> PATTERN ADOPTION & MAINTENANCE
-> OBSERVER / OBSERVED INTELLIGENCE
-> RELATIONAL KNOWLEDGE GRAPH
-> MULTI-LENS ANALYSIS WHEN RELEVANT
-> EPISTEMIC CLASSIFICATION
-> CONFIDENCE CALIBRATION
-> META-OBSERVATIONAL INTEGRITY AUDIT
-> OBSERVATIONAL REPORT
-> STOP
```

The internal complexity must remain evidence-driven. Advanced layers should be omitted when material is insufficient rather than populated speculatively. Internal rigor must not become interface overload.

## Where every report ends

> PCI boundary reached: the report ends at observation. No prescription is generated.

## The test for every feature

Does this feature make available material more visible, or does it begin deciding what the material requires the person to do? The first remains inside PCI. The second crosses the PCI boundary. That distinction exists not only as philosophy, but in schemas, prompts, validators, interface behavior, tests, release gates, and governance.$pci$, $pci$canonical$pci$, $pci$2026.09.25$pci$, 'published', $pci$Seeded from Blueprint §1.3, §2.1, §4.9$pci$ from public.content_items where slug = $pci$processing-boundary$pci$
on conflict (content_id, content_version) do nothing;
update public.content_items set status = 'published' where slug = $pci$processing-boundary$pci$ and status = 'approved';

insert into public.content_items (slug, type, collection, title, summary, canon_status, status, chapter_order, current_version)
values ($pci$constitutional-invariants$pci$, $pci$framework$pci$, $pci$pci-framework$pci$, $pci$Constitutional Invariants$pci$, $pci$Fifteen transformations the PCI Engine does not perform unless independently supported by appropriate evidence.$pci$, $pci$canonical$pci$, $pci$approved$pci$, 4, 1)
on conflict (slug) do nothing;
insert into public.content_versions (content_id, content_version, title, body, canon_status, canon_version, status, change_note)
select id, 1, $pci$Constitutional Invariants$pci$, $pci$The following transformations are prohibited unless independently supported by appropriate evidence. They are enforced in prompt contracts, output schemas, validators, tests, and final report language.

- correlation → causation
- sequence → mechanism
- recurrence → origin
- similarity → transmission
- behavior → permanent identity
- identity language → ontology
- interpretation → direct observation
- symbol → fact
- philosophical coherence → empirical proof
- confidence → certainty
- contradiction → pathology
- emotion → error
- pattern → diagnosis
- visibility → obligation
- observation → prescription

## Output that is rejected or quarantined

Output that crosses the PCI boundary or exceeds available evidence is rejected or quarantined. Examples include:

- You should…
- You need to…
- You must… (except engine rules)
- The right thing is…
- This means you are…
- Your true self is…
- You suffer from…
- The solution is…
- You need to heal / fix / overcome…
- A pattern proves an origin or diagnosis.

## No prescriptive fields

There is deliberately no recommendation, treatment, action plan, best choice, behavioral prescription, personality score, or alignment score field in the PCI observation schema. An output that carries one is invalid by construction.$pci$, $pci$canonical$pci$, $pci$2026.09.25$pci$, 'published', $pci$Seeded from Blueprint §2.2, §8.3$pci$ from public.content_items where slug = $pci$constitutional-invariants$pci$
on conflict (content_id, content_version) do nothing;
update public.content_items set status = 'published' where slug = $pci$constitutional-invariants$pci$ and status = 'approved';

insert into public.content_items (slug, type, collection, title, summary, canon_status, status, chapter_order, current_version)
values ($pci$epistemic-classes$pci$, $pci$framework$pci$, $pci$pci-framework$pci$, $pci$Epistemic Classes and Confidence$pci$, $pci$What is evidenced, reported, inferred, interpreted, symbolic, philosophical, speculative or unknown — and how strongly it is supported.$pci$, $pci$canonical$pci$, $pci$approved$pci$, 5, 1)
on conflict (slug) do nothing;
insert into public.content_versions (content_id, content_version, title, body, canon_status, canon_version, status, change_note)
select id, 1, $pci$Epistemic Classes and Confidence$pci$, $pci$The internal engine retains more precise epistemic classes than the simplified user-facing labels of the Epistemic Ledger (evidence, interpretation, inference, hypothesis, symbolic, philosophical, unknown).

## Internal classes

- **DIRECT** — Explicitly present in supplied material. Maps to evidence.
- **SELF_REPORTED** — Evidence that an internal state, motive, memory, or event was reported; not external verification.
- **INFERRED** — Reasonable interpretation supported but not directly established.
- **PATTERN_SUPPORTED** — Inference supported across multiple materially relevant observations.
- **INTERPRETIVE** — Conceptual frame used to organize material.
- **SYMBOLIC** — Metaphorical, mythological, archetypal, artistic, dream-based, or symbolic reading.
- **PHILOSOPHICAL** — Proposition about meaning, ontology, consciousness, agency, identity, or existence.
- **SPECULATIVE** — Possible explanation with limited support.
- **UNKNOWN** — Cannot presently be established.

## Confidence calibration

Confidence is categorical rather than a fabricated numerical precision. The labels are:

- High Support
- Moderate Support
- Limited Support
- Insufficient Evidence
- Undetermined

A confidence label describes the support available in the material. It is never certainty.$pci$, $pci$canonical$pci$, $pci$2026.09.25$pci$, 'published', $pci$Seeded from Blueprint §4.6, §4.7$pci$ from public.content_items where slug = $pci$epistemic-classes$pci$
on conflict (content_id, content_version) do nothing;
update public.content_items set status = 'published' where slug = $pci$epistemic-classes$pci$ and status = 'approved';

insert into public.content_items (slug, type, collection, title, summary, canon_status, status, chapter_order, current_version)
values ($pci$structured-observation-records$pci$, $pci$framework$pci$, $pci$pci-framework$pci$, $pci$Structured Observation Records$pci$, $pci$Every meaningful unit of material can become a traceable record: OBS-001, OBS-002, and so on.$pci$, $pci$canonical$pci$, $pci$approved$pci$, 6, 1)
on conflict (slug) do nothing;
insert into public.content_versions (content_id, content_version, title, body, canon_status, canon_version, status, change_note)
select id, 1, $pci$Structured Observation Records$pci$, $pci$Every meaningful unit of material should be convertible into a traceable observation record. Records use local identifiers such as OBS-001, OBS-002, and so on.

## Fields

- **Source type** — Journal entry, statement, conversation, event, decision, creative work, symbolic material, and so on.
- **Time reference** — Exact date/time, relative time, sequence position, or unknown.
- **Event / direct observation** — What is described or directly present without interpretive expansion.
- **Interpretation** — Meaning assigned to the event.
- **Emotion** — Reported affective experience; inferred only when explicitly marked.
- **Judgment** — Cognitive evaluation, categorization, comparison, conclusion, or valuation.
- **Assumptions** — Premises used without direct verification.
- **Identity attribution** — Claims that convert an event, behavior, role, or feeling into what a person or entity is.
- **Behavior** — Actions, omissions, responses, decisions, and interaction patterns.
- **Context** — Conditions that can materially alter interpretation.
- **Unknown variables** — Relevant absent, inaccessible, contradictory, ambiguous, or unknowable facts.
- **Evidence anchors** — Source statements or passages that support the record.

## Immutable evidence, revisable analysis

```
Raw Entry — immutable
Analysis v1 — revisable model
Analysis v2 — revised model
…
Observational Report — current representation of available material
```

New information creates a new analysis version. It does not silently rewrite the original input or erase previous interpretations.$pci$, $pci$canonical$pci$, $pci$2026.09.25$pci$, 'published', $pci$Seeded from Blueprint §4.1, §7.4, §7.5$pci$ from public.content_items where slug = $pci$structured-observation-records$pci$
on conflict (content_id, content_version) do nothing;
update public.content_items set status = 'published' where slug = $pci$structured-observation-records$pci$ and status = 'approved';

insert into public.content_items (slug, type, collection, title, summary, canon_status, status, chapter_order, current_version)
values ($pci$time-and-context$pci$, $pci$framework$pci$, $pci$pci-framework$pci$, $pci$Temporal Intelligence and Context Differential$pci$, $pci$Recurrence is classified carefully, and similar events are not treated as equivalent until their context is compared.$pci$, $pci$canonical$pci$, $pci$approved$pci$, 7, 1)
on conflict (slug) do nothing;
insert into public.content_versions (content_id, content_version, title, body, canon_status, canon_version, status, change_note)
select id, 1, $pci$Temporal Intelligence and Context Differential$pci$, $pci$## Temporal intelligence

When chronology is sufficient, recurrence is classified carefully:

- isolated event
- repeated event
- emerging pattern
- historical pattern
- resurfacing pattern
- interrupted pattern
- pattern transformation
- surface recurrence / structural difference
- structural recurrence / surface difference

Historical material must not be presented as if it necessarily represents the present.

## Context differential

For apparently similar observations, the engine reports:

- constants
- changed conditions
- context-sensitive features
- context-invariant features
- missing comparison variables

Similar events are not structurally equivalent until relevant context is compared.

## Comparison is not causation

Contextual comparison asks where something structurally similar has appeared before, and what was the same or different about the context. It compares without treating similarity as causation or sameness.$pci$, $pci$canonical$pci$, $pci$2026.09.25$pci$, 'published', $pci$Seeded from Blueprint §4.2, §4.4$pci$ from public.content_items where slug = $pci$time-and-context$pci$
on conflict (content_id, content_version) do nothing;
update public.content_items set status = 'published' where slug = $pci$time-and-context$pci$ and status = 'approved';

insert into public.content_items (slug, type, collection, title, summary, canon_status, status, chapter_order, current_version)
values ($pci$contradiction-engine$pci$, $pci$framework$pci$, $pci$pci-framework$pci$, $pci$The Contradiction Engine$pci$, $pci$Contradiction exists to expose tension, not to force one side to be false.$pci$, $pci$canonical$pci$, $pci$approved$pci$, 8, 1)
on conflict (slug) do nothing;
insert into public.content_versions (content_id, content_version, title, body, canon_status, canon_version, status, change_note)
select id, 1, $pci$The Contradiction Engine$pci$, $pci$Contradiction exists to expose tension, not to force one side to be false.

## Supported classes

- direct contradiction
- stated-position / behavior discrepancy
- value / behavior discrepancy
- interpretation conflict
- identity conflict
- temporal revision
- perspective contradiction
- context-dependent opposition
- unresolved tension

## Before labelling a contradiction

Before labelling contradiction, compare:

- subject
- meaning
- scope
- time
- context
- observer position

Two statements that oppose each other on the surface may differ in time (a revision), in context (a context-dependent opposition), or in subject. The label follows from the comparison.

## Contradiction is not pathology

Contradictions remain visible rather than automatically reconciled. A contradiction is material; it is not evidence of a disorder, a flaw, or dishonesty.$pci$, $pci$canonical$pci$, $pci$2026.09.25$pci$, 'published', $pci$Seeded from Blueprint §4.3$pci$ from public.content_items where slug = $pci$contradiction-engine$pci$
on conflict (content_id, content_version) do nothing;
update public.content_items set status = 'published' where slug = $pci$contradiction-engine$pci$ and status = 'approved';

insert into public.content_items (slug, type, collection, title, summary, canon_status, status, chapter_order, current_version)
values ($pci$observer-observed$pci$, $pci$framework$pci$, $pci$pci-framework$pci$, $pci$Observer / Observed$pci$, $pci$PCI may observe how meaning is produced without pathologizing the observer.$pci$, $pci$canonical$pci$, $pci$approved$pci$, 9, 1)
on conflict (slug) do nothing;
insert into public.content_versions (content_id, content_version, title, body, canon_status, canon_version, status, change_note)
select id, 1, $pci$Observer / Observed$pci$, $pci$Where relevant, the engine distinguishes:

- observed event
- observer position
- attention selection
- perceptual frame
- interpretive frame
- expectation
- meaning assignment
- observer identity involvement
- state dependency
- self-observation
- any supported observer / observed feedback loop

PCI may observe how meaning is produced without pathologizing the observer.

## Second-order observation

The observer can itself become observable material. When a person reports noticing their own process — "I caught myself", "I noticed I was doing it again" — that self-observation is part of the record, alongside what was observed.$pci$, $pci$canonical$pci$, $pci$2026.09.25$pci$, 'published', $pci$Seeded from Blueprint §4.5$pci$ from public.content_items where slug = $pci$observer-observed$pci$
on conflict (content_id, content_version) do nothing;
update public.content_items set status = 'published' where slug = $pci$observer-observed$pci$ and status = 'approved';

insert into public.content_items (slug, type, collection, title, summary, canon_status, status, chapter_order, current_version)
values ($pci$integrity-audit-and-report$pci$, $pci$framework$pci$, $pci$pci-framework$pci$, $pci$The Integrity Audit and the Observational Report$pci$, $pci$One controlled self-audit before the report is finalised, and a report that ends at observation.$pci$, $pci$canonical$pci$, $pci$approved$pci$, 10, 1)
on conflict (slug) do nothing;
insert into public.content_versions (content_id, content_version, title, body, canon_status, canon_version, status, change_note)
select id, 1, $pci$The Integrity Audit and the Observational Report$pci$, $pci$## Meta-Observational Integrity Audit

Before finalizing the report, the engine performs one controlled self-audit. The audit checks:

- inference inflation
- interpretation leakage
- lens contamination
- identity inflation
- narrative coherence bias
- pattern overfitting
- context collapse
- confirmation loops
- counter-hypotheses
- disconfirming evidence

Material corrections are surfaced only when they materially alter the report.

## The observational report

The mature report may include the following sections when materially populated:

- Observed Material
- Structured Observation Records
- Temporal Findings
- Contradictions and Tensions
- Context Differential
- Relational Findings
- Pattern Adoption and Maintenance
- Observer / Observed Findings
- Relational Graph Findings
- Lens Comparison (when used)
- Meta-Observational Integrity Audit
- Epistemic Ledger
- What Became Visible
- Boundary

> PCI boundary reached: the report ends at observation. No prescription is generated.$pci$, $pci$canonical$pci$, $pci$2026.09.25$pci$, 'published', $pci$Seeded from Blueprint §4.8, §4.9$pci$ from public.content_items where slug = $pci$integrity-audit-and-report$pci$
on conflict (content_id, content_version) do nothing;
update public.content_items set status = 'published' where slug = $pci$integrity-audit-and-report$pci$ and status = 'approved';

insert into public.content_items (slug, type, collection, title, summary, canon_status, status, chapter_order, current_version)
values ($pci$on-the-contrary$pci$, $pci$framework$pci$, $pci$pci-framework$pci$, $pci$On the Contrary$pci$, $pci$A contained examination of an apparent error, imbalance, problem, unwanted event, or contradiction within a wider relational system.$pci$, $pci$canonical$pci$, $pci$approved$pci$, 11, 1)
on conflict (slug) do nothing;
insert into public.content_versions (content_id, content_version, title, body, canon_status, canon_version, status, change_note)
select id, 1, $pci$On the Contrary$pci$, $pci$On the Contrary is a contained mini-application for examining an apparent error, imbalance, problem, unwanted event, or contradiction within a wider relational system.

```
IDENTIFIED ERROR -> IMPLIED EXPECTATION -> MISSING VARIABLES -> SYSTEM RELATIONSHIP -> CONTRARY POSITION -> BALANCE
```

## Balance

Balance describes relationship within a system. It does not automatically mean fairness, desirability, approval, justice, health, morality, correctness, comfort, or forced positivity.

The engine must not erase harm or coerce negative material into a positive interpretation.

## What On the Contrary is tested against

Sessions are tested against forced positivity, victim-blaming, harm erasure, false equivalence, and prescriptive output. Balance is not presented as moral approval.$pci$, $pci$canonical$pci$, $pci$2026.09.25$pci$, 'published', $pci$Seeded from Blueprint §3.5, §15$pci$ from public.content_items where slug = $pci$on-the-contrary$pci$
on conflict (content_id, content_version) do nothing;
update public.content_items set status = 'published' where slug = $pci$on-the-contrary$pci$ and status = 'approved';

insert into public.content_items (slug, type, collection, title, summary, canon_status, status, chapter_order, current_version)
values ($pci$pattern-adoption$pci$, $pci$framework$pci$, $pci$pci-framework$pci$, $pci$Pattern Adoption$pci$, $pci$An analytical sub-engine, not a personality label. Recurrence alone never establishes origin.$pci$, $pci$canonical$pci$, $pci$approved$pci$, 12, 1)
on conflict (slug) do nothing;
insert into public.content_versions (content_id, content_version, title, body, canon_status, canon_version, status, change_note)
select id, 1, $pci$Pattern Adoption$pci$, $pci$Pattern Adoption operates as an analytical sub-engine rather than a personality label. The current model:

```
Signal -> Recurrence -> Reinforcement -> Defaulting -> Integration -> Identification -> Preservation -> Visibility -> Revision
```

The engine may examine candidate adoption pathways, current activation and reinforcement conditions, absence conditions, context dependence, and cross-context recurrence. It must not infer origin from recurrence alone.

## Viewing patterns

A pattern is shown with its recurrence, context, confidence, activation, absence and revision history. Patterns remain revisable and are not identity claims. Stages that the material does not evidence are left unevidenced rather than inferred.$pci$, $pci$canonical$pci$, $pci$2026.09.25$pci$, 'published', $pci$Seeded from Blueprint §3.6, §16$pci$ from public.content_items where slug = $pci$pattern-adoption$pci$
on conflict (content_id, content_version) do nothing;
update public.content_items set status = 'published' where slug = $pci$pattern-adoption$pci$ and status = 'approved';

insert into public.content_items (slug, type, collection, title, summary, canon_status, status, chapter_order, current_version)
values ($pci$relational-intelligence$pci$, $pci$framework$pci$, $pci$pci-framework$pci$, $pci$Relational Intelligence and the Cognitive Twin$pci$, $pci$With explicit permission, current material can be compared with previous material — transparently, traceably, and revisably.$pci$, $pci$canonical$pci$, $pci$approved$pci$, 13, 1)
on conflict (slug) do nothing;
insert into public.content_versions (content_id, content_version, title, body, canon_status, canon_version, status, change_note)
select id, 1, $pci$Relational Intelligence and the Cognitive Twin$pci$, $pci$With explicit user permission, the system can compare current material against previous material. Relationship types include RELATED TO, CONTRADICTS, REPEATS, EXPANDS, PRECEDES, FOLLOWS, SAME CONTEXT, DIFFERENT CONTEXT, REFERENCES, SUPPORTED BY, CHALLENGED BY, CHANGES UNDER, and ABSENT UNDER.

A graph edge records a visible relationship; it is not automatically a causal mechanism.

## Conditions

- Every relationship is traceable to source material.
- Users can disable longitudinal comparison.
- Patterns remain revisable and are not identity claims.
- Contradictions remain visible rather than automatically reconciled.
- Historical material is not presented as current fact.

## Causal intelligence

```
Observed Sequence -> Candidate Mechanism -> Supporting Evidence -> Alternative Mechanism -> Disconfirming Evidence -> Confidence
```

Sequence is not causation. Causal relationships remain hypotheses unless independently demonstrated.

## The Cognitive Twin

The Cognitive Twin is an advanced, opt-in, revisable structural model generated from available material. It is not a declaration of the user's true self or essence. It is enabled only after enough longitudinal data exists and only by explicit opt-in. Every structural claim stores supporting observations, contradictory observations, epistemic class, confidence, context, first observed, last observed, and revision history.

## Self-correcting theory

```
Previous Interpretation -> New Evidence -> Compatibility Test -> Support / Narrow / Contradict / Dissolve -> New Model Version
```

Earlier model versions are preserved. The application does not silently rewrite the user's analytical history.$pci$, $pci$canonical$pci$, $pci$2026.09.25$pci$, 'published', $pci$Seeded from Blueprint §3.8, §3.9, §16, §18$pci$ from public.content_items where slug = $pci$relational-intelligence$pci$
on conflict (content_id, content_version) do nothing;
update public.content_items set status = 'published' where slug = $pci$relational-intelligence$pci$ and status = 'approved';

insert into public.content_items (slug, type, collection, title, summary, canon_status, status, chapter_order, current_version)
values ($pci$multi-lens-analysis$pci$, $pci$framework$pci$, $pci$pci-framework$pci$, $pci$Multi-Lens Analysis$pci$, $pci$Optional lenses produce findings under their own labels before any comparison across lenses.$pci$, $pci$canonical$pci$, $pci$approved$pci$, 14, 1)
on conflict (slug) do nothing;
insert into public.content_versions (content_id, content_version, title, body, canon_status, canon_version, status, change_note)
select id, 1, $pci$Multi-Lens Analysis$pci$, $pci$Optional lenses — PCI structural, cognitive, behavioral, systems, relational, identity, creative-process, Jungian / archetypal / shadow, mythological, and philosophical — must produce findings under their own labels before cross-lens comparison.

Findings remain isolated by lens before comparing convergence, divergence, orthogonality and epistemic asymmetry.

## What a lens cannot do

- Symbolic resonance does not become empirical evidence.
- Philosophical coherence does not become scientific proof.
- Behavioral recurrence does not become diagnosis.

A lens organises material from one standpoint. It adds a way of looking, not additional evidence.$pci$, $pci$canonical$pci$, $pci$2026.09.25$pci$, 'published', $pci$Seeded from Blueprint §8.4, §18$pci$ from public.content_items where slug = $pci$multi-lens-analysis$pci$
on conflict (content_id, content_version) do nothing;
update public.content_items set status = 'published' where slug = $pci$multi-lens-analysis$pci$ and status = 'approved';

insert into public.content_items (slug, type, collection, title, summary, canon_status, status, chapter_order, current_version)
values ($pci$canon-governance$pci$, $pci$framework$pci$, $pci$pci-framework$pci$, $pci$Canon Governance$pci$, $pci$PCI content and engine behaviour carry explicit canon status so the framework can evolve without silent drift.$pci$, $pci$canonical$pci$, $pci$approved$pci$, 15, 1)
on conflict (slug) do nothing;
insert into public.content_versions (content_id, content_version, title, body, canon_status, canon_version, status, change_note)
select id, 1, $pci$Canon Governance$pci$, $pci$PCI content and engine behavior carry explicit canon status so the framework can evolve without silent drift.

## Canon statuses

- **Canonical** — Explicitly established PCI doctrine or terminology.
- **Derived** — Follows from canonical principles but is not independently canonical.
- **Extended** — Deliberately expands an established canonical concept.
- **Provisional** — Proposed but not yet sufficiently integrated or tested.
- **External comparison** — Belongs to another framework and is used comparatively.
- **Contradictory** — Conflicts with current canon as written.
- **Deprecated** — Former PCI framing intentionally superseded by a newer version.

A concept should not be silently promoted from provisional to canonical. Canon change should preserve a traceable revision history, epistemic class, contradiction analysis, and explicit author approval.

## Release gates

- **Canon** — Is the current PCI canon represented correctly, with obsolete architecture inactive?
- **Functional** — Does the feature work across normal and error states?
- **Epistemic** — Are evidence, interpretation, uncertainty, patterns and contradictions represented without overreach?
- **Security** — Is private material isolated, deletable, exportable and protected from client-side secrets and leaks?
- **Operational** — Can the release be monitored, backed up, rolled back and supported in production?$pci$, $pci$canonical$pci$, $pci$2026.09.25$pci$, 'published', $pci$Seeded from Blueprint §1.4, §19.3$pci$ from public.content_items where slug = $pci$canon-governance$pci$
on conflict (content_id, content_version) do nothing;
update public.content_items set status = 'published' where slug = $pci$canon-governance$pci$ and status = 'approved';

insert into public.content_items (slug, type, collection, title, summary, canon_status, status, chapter_order, current_version)
values ($pci$introduction$pci$, $pci$front_matter$pci$, $pci$art-of-being$pci$, $pci$Introduction$pci$, $pci$Introduction to The Art of Being.$pci$, $pci$canonical$pci$, $pci$draft$pci$, 0, null)
on conflict (slug) do nothing;

insert into public.content_items (slug, type, collection, title, summary, canon_status, status, chapter_order, current_version)
values ($pci$chapter-01$pci$, $pci$chapter$pci$, $pci$art-of-being$pci$, $pci$Discover Your Hidden Abilities$pci$, $pci$Discovery and visibility of capacity before premature identity conclusions.$pci$, $pci$canonical$pci$, $pci$draft$pci$, 1, null)
on conflict (slug) do nothing;

insert into public.content_items (slug, type, collection, title, summary, canon_status, status, chapter_order, current_version)
values ($pci$chapter-02$pci$, $pci$chapter$pci$, $pci$art-of-being$pci$, $pci$The AAA Method — Adopt, Allow, Align$pci$, $pci$The established AAA method within the current PCI canon.$pci$, $pci$canonical$pci$, $pci$draft$pci$, 2, null)
on conflict (slug) do nothing;

insert into public.content_items (slug, type, collection, title, summary, canon_status, status, chapter_order, current_version)
values ($pci$chapter-03$pci$, $pci$chapter$pci$, $pci$art-of-being$pci$, $pci$Being Is Becoming$pci$, $pci$Centered on the formulation: Being is Manifested; Becoming is Manufactured.$pci$, $pci$canonical$pci$, $pci$draft$pci$, 3, null)
on conflict (slug) do nothing;

insert into public.content_items (slug, type, collection, title, summary, canon_status, status, chapter_order, current_version)
values ($pci$chapter-04$pci$, $pci$chapter$pci$, $pci$art-of-being$pci$, $pci$Practice as a Mythology$pci$, $pci$Repetition, learning, adaptation, and cultural myths surrounding forced practice.$pci$, $pci$canonical$pci$, $pci$draft$pci$, 4, null)
on conflict (slug) do nothing;

insert into public.content_items (slug, type, collection, title, summary, canon_status, status, chapter_order, current_version)
values ($pci$chapter-05$pci$, $pci$chapter$pci$, $pci$art-of-being$pci$, $pci$You Were Finished at Birth$pci$, $pci$PCI material concerning completeness, construction, and becoming.$pci$, $pci$canonical$pci$, $pci$draft$pci$, 5, null)
on conflict (slug) do nothing;

insert into public.content_items (slug, type, collection, title, summary, canon_status, status, chapter_order, current_version)
values ($pci$chapter-06$pci$, $pci$chapter$pci$, $pci$art-of-being$pci$, $pci$Darkness Is an Opportunity to Shine$pci$, $pci$Shadow material, Jungian reference, projection, visibility, and unseen psychological material, with symbolic claims kept epistemically bounded.$pci$, $pci$canonical$pci$, $pci$draft$pci$, 6, null)
on conflict (slug) do nothing;

insert into public.content_items (slug, type, collection, title, summary, canon_status, status, chapter_order, current_version)
values ($pci$chapter-07$pci$, $pci$chapter$pci$, $pci$art-of-being$pci$, $pci$Individualism — The Courage to Claim Who You Are$pci$, $pci$Individuality without requiring a permanently fixed true-self ontology.$pci$, $pci$canonical$pci$, $pci$draft$pci$, 7, null)
on conflict (slug) do nothing;

insert into public.content_items (slug, type, collection, title, summary, canon_status, status, chapter_order, current_version)
values ($pci$chapter-08$pci$, $pci$chapter$pci$, $pci$art-of-being$pci$, $pci$The Principle of Balance$pci$, $pci$Balance as systemic relationship rather than moral approval.$pci$, $pci$canonical$pci$, $pci$draft$pci$, 8, null)
on conflict (slug) do nothing;

insert into public.content_items (slug, type, collection, title, summary, canon_status, status, chapter_order, current_version)
values ($pci$chapter-09$pci$, $pci$chapter$pci$, $pci$art-of-being$pci$, $pci$Identity — The Field of Possibilities$pci$, $pci$Identity as active configuration and field of possibilities rather than permanently finished object.$pci$, $pci$canonical$pci$, $pci$draft$pci$, 9, null)
on conflict (slug) do nothing;

insert into public.content_items (slug, type, collection, title, summary, canon_status, status, chapter_order, current_version)
values ($pci$chapter-10$pci$, $pci$chapter$pci$, $pci$art-of-being$pci$, $pci$Growth Is Effortless$pci$, $pci$Organic development contrasted with forced repetition and externally manufactured standards of progress; linked to Practice as a Mythology.$pci$, $pci$canonical$pci$, $pci$draft$pci$, 10, null)
on conflict (slug) do nothing;

insert into public.content_items (slug, type, collection, title, summary, canon_status, status, chapter_order, current_version)
values ($pci$chapter-11$pci$, $pci$chapter$pci$, $pci$art-of-being$pci$, $pci$You Are Bound to Choose / Perpetual Becoming$pci$, $pci$Choice, participation, and continuing becoming.$pci$, $pci$canonical$pci$, $pci$draft$pci$, 11, null)
on conflict (slug) do nothing;

insert into public.content_items (slug, type, collection, title, summary, canon_status, status, chapter_order, current_version)
values ($pci$chapter-12$pci$, $pci$chapter$pci$, $pci$art-of-being$pci$, $pci$The Neutral Gateway / Neutrality and Subtlety — The Forgotten Power$pci$, $pci$Neutrality as observational space rather than emotional absence; subtlety as a neglected mode of perception.$pci$, $pci$canonical$pci$, $pci$draft$pci$, 12, null)
on conflict (slug) do nothing;

insert into public.content_items (slug, type, collection, title, summary, canon_status, status, chapter_order, current_version)
values ($pci$chapter-13$pci$, $pci$chapter$pci$, $pci$art-of-being$pci$, $pci$The Observer Gets Observed / Judgment as Cognitive Processing$pci$, $pci$Judgment treated as cognitive processing, while the observer itself becomes observable material.$pci$, $pci$canonical$pci$, $pci$draft$pci$, 13, null)
on conflict (slug) do nothing;

insert into public.content_items (slug, type, collection, title, summary, canon_status, status, chapter_order, current_version)
values ($pci$chapter-14$pci$, $pci$chapter$pci$, $pci$art-of-being$pci$, $pci$The Illusion of Challenge / Problem Is a Construct / Emotion as Feedback / Emotion Without Possession$pci$, $pci$Distinguishes event from classification, while examining emotion as information without compulsory identity possession.$pci$, $pci$canonical$pci$, $pci$draft$pci$, 14, null)
on conflict (slug) do nothing;

insert into public.content_items (slug, type, collection, title, summary, canon_status, status, chapter_order, current_version)
values ($pci$chapter-15$pci$, $pci$chapter$pci$, $pci$art-of-being$pci$, $pci$Repetition Is Not Repetition$pci$, $pci$External repetition may look identical while organism, context, skill, information, perception, and relationship to the act change.$pci$, $pci$canonical$pci$, $pci$draft$pci$, 15, null)
on conflict (slug) do nothing;

insert into public.content_items (slug, type, collection, title, summary, canon_status, status, chapter_order, current_version)
values ($pci$chapter-16$pci$, $pci$chapter$pci$, $pci$art-of-being$pci$, $pci$To Sing Is to Breathe; To Breathe Is to Be$pci$, $pci$Conscious breathing, embodiment, seven embodied plus five higher energy centers within the supplied framework, full-body breathing, full-body voice, performance, presence, self-consciousness, and Being.$pci$, $pci$canonical$pci$, $pci$draft$pci$, 16, null)
on conflict (slug) do nothing;

insert into public.content_items (slug, type, collection, title, summary, canon_status, status, chapter_order, current_version)
values ($pci$book-glossary$pci$, $pci$back_matter$pci$, $pci$art-of-being$pci$, $pci$Glossary$pci$, $pci$The book’s glossary.$pci$, $pci$canonical$pci$, $pci$draft$pci$, 17, null)
on conflict (slug) do nothing;

insert into public.content_items (slug, type, collection, title, summary, canon_status, status, chapter_order, current_version)
values ($pci$appendix$pci$, $pci$back_matter$pci$, $pci$art-of-being$pci$, $pci$Appendix$pci$, $pci$Appendix.$pci$, $pci$canonical$pci$, $pci$draft$pci$, 18, null)
on conflict (slug) do nothing;

insert into public.content_items (slug, type, collection, title, summary, canon_status, status, chapter_order, current_version)
values ($pci$references$pci$, $pci$back_matter$pci$, $pci$art-of-being$pci$, $pci$References$pci$, $pci$References.$pci$, $pci$canonical$pci$, $pci$draft$pci$, 19, null)
on conflict (slug) do nothing;

insert into public.glossary_terms (slug, term, definition, canon_status, status) values ($pci$pci$pci$, $pci$Psycho-Creative Intelligence (PCI)$pci$, $pci$The framework behind PCI Academy. As software, an observational intelligence environment: it receives human material, separates its components, compares it across context and time where evidence permits, distinguishes evidence from interpretation, surfaces patterns and contradictions, and produces an observational report — then stops.$pci$, $pci$canonical$pci$, 'published') on conflict (slug) do nothing;
insert into public.glossary_terms (slug, term, definition, canon_status, status) values ($pci$visibility$pci$, $pci$Visibility$pci$, $pci$The output of PCI. PCI may make structure visible; it may not convert visibility into behavioral obligation.$pci$, $pci$canonical$pci$, 'published') on conflict (slug) do nothing;
insert into public.glossary_terms (slug, term, definition, canon_status, status) values ($pci$prescription$pci$, $pci$Prescription$pci$, $pci$Any recommendation, treatment, action plan, best choice or behavioral direction. Prescription lies outside the PCI Engine; "observation → prescription" is a prohibited transformation.$pci$, $pci$derived$pci$, 'published') on conflict (slug) do nothing;
insert into public.glossary_terms (slug, term, definition, canon_status, status) values ($pci$stop-boundary$pci$, $pci$STOP boundary$pci$, $pci$The point at which PCI processing ends: after the observational report. Any choice, action, strategy, intervention, recommendation, or behavioral direction that follows belongs outside the PCI Engine.$pci$, $pci$canonical$pci$, 'published') on conflict (slug) do nothing;
insert into public.glossary_terms (slug, term, definition, canon_status, status) values ($pci$input$pci$, $pci$Input$pci$, $pci$The first operation. What actually occurred, or what material is present, before explaining what it means. Principle: preserve the raw material before explanation.$pci$, $pci$canonical$pci$, 'published') on conflict (slug) do nothing;
insert into public.glossary_terms (slug, term, definition, canon_status, status) values ($pci$decomposition$pci$, $pci$Decomposition$pci$, $pci$The second operation. Separating event, behavior, interpretation, emotion, judgment, assumption, context, identity attribution, and unknown — categories commonly experienced as a single narrative.$pci$, $pci$canonical$pci$, 'published') on conflict (slug) do nothing;
insert into public.glossary_terms (slug, term, definition, canon_status, status) values ($pci$contextual-comparison$pci$, $pci$Contextual Comparison$pci$, $pci$The third operation. Where something structurally similar has appeared before, and what was the same or different about the context. Compares without treating similarity as causation or sameness.$pci$, $pci$canonical$pci$, 'published') on conflict (slug) do nothing;
insert into public.glossary_terms (slug, term, definition, canon_status, status) values ($pci$pattern-detection$pci$, $pci$Pattern Detection$pci$, $pci$The fourth operation. What appears to repeat across the available material, and under what conditions. Reports recurrence without converting it into identity.$pci$, $pci$canonical$pci$, 'published') on conflict (slug) do nothing;
insert into public.glossary_terms (slug, term, definition, canon_status, status) values ($pci$contradiction-detection$pci$, $pci$Contradiction Detection$pci$, $pci$The fifth operation. What parts of the material appear inconsistent, incompatible, revised, or unresolved when compared. Exposes tension without forcing resolution.$pci$, $pci$canonical$pci$, 'published') on conflict (slug) do nothing;
insert into public.glossary_terms (slug, term, definition, canon_status, status) values ($pci$evidentiary-separation$pci$, $pci$Evidentiary Separation$pci$, $pci$The sixth operation. What is directly evidenced, what is interpreted or inferred, what remains hypothetical or symbolic, and what is presently unknown. Protects epistemic classes.$pci$, $pci$canonical$pci$, 'published') on conflict (slug) do nothing;
insert into public.glossary_terms (slug, term, definition, canon_status, status) values ($pci$observational-report$pci$, $pci$Observational Report$pci$, $pci$The seventh operation. What can actually be observed without deciding what the person should think, become, choose, or do. Returns visibility and stops.$pci$, $pci$canonical$pci$, 'published') on conflict (slug) do nothing;
insert into public.glossary_terms (slug, term, definition, canon_status, status) values ($pci$structured-observation-record$pci$, $pci$Structured Observation Record$pci$, $pci$A traceable record of one meaningful unit of material (OBS-001, OBS-002…), holding source type, time reference, event, interpretation, emotion, judgment, assumptions, identity attribution, behavior, context, unknown variables and evidence anchors.$pci$, $pci$canonical$pci$, 'published') on conflict (slug) do nothing;
insert into public.glossary_terms (slug, term, definition, canon_status, status) values ($pci$event$pci$, $pci$Event / direct observation$pci$, $pci$What is described or directly present without interpretive expansion.$pci$, $pci$canonical$pci$, 'published') on conflict (slug) do nothing;
insert into public.glossary_terms (slug, term, definition, canon_status, status) values ($pci$interpretation$pci$, $pci$Interpretation$pci$, $pci$Meaning assigned to an event.$pci$, $pci$canonical$pci$, 'published') on conflict (slug) do nothing;
insert into public.glossary_terms (slug, term, definition, canon_status, status) values ($pci$emotion$pci$, $pci$Emotion$pci$, $pci$Reported affective experience; inferred only when explicitly marked. An emotion is material, not an error.$pci$, $pci$canonical$pci$, 'published') on conflict (slug) do nothing;
insert into public.glossary_terms (slug, term, definition, canon_status, status) values ($pci$judgment$pci$, $pci$Judgment$pci$, $pci$Cognitive evaluation, categorization, comparison, conclusion, or valuation.$pci$, $pci$canonical$pci$, 'published') on conflict (slug) do nothing;
insert into public.glossary_terms (slug, term, definition, canon_status, status) values ($pci$assumption$pci$, $pci$Assumption$pci$, $pci$A premise used without direct verification.$pci$, $pci$canonical$pci$, 'published') on conflict (slug) do nothing;
insert into public.glossary_terms (slug, term, definition, canon_status, status) values ($pci$identity-attribution$pci$, $pci$Identity attribution$pci$, $pci$A claim that converts an event, behavior, role, or feeling into what a person or entity is.$pci$, $pci$canonical$pci$, 'published') on conflict (slug) do nothing;
insert into public.glossary_terms (slug, term, definition, canon_status, status) values ($pci$behavior$pci$, $pci$Behavior$pci$, $pci$Actions, omissions, responses, decisions, and interaction patterns.$pci$, $pci$canonical$pci$, 'published') on conflict (slug) do nothing;
insert into public.glossary_terms (slug, term, definition, canon_status, status) values ($pci$context$pci$, $pci$Context$pci$, $pci$Conditions that can materially alter interpretation.$pci$, $pci$canonical$pci$, 'published') on conflict (slug) do nothing;
insert into public.glossary_terms (slug, term, definition, canon_status, status) values ($pci$unknown-variable$pci$, $pci$Unknown variable$pci$, $pci$A relevant absent, inaccessible, contradictory, ambiguous, or unknowable fact.$pci$, $pci$canonical$pci$, 'published') on conflict (slug) do nothing;
insert into public.glossary_terms (slug, term, definition, canon_status, status) values ($pci$evidence-anchor$pci$, $pci$Evidence anchor$pci$, $pci$The source statement or passage that supports a record or finding. In this application, an anchor must quote the material verbatim.$pci$, $pci$derived$pci$, 'published') on conflict (slug) do nothing;
insert into public.glossary_terms (slug, term, definition, canon_status, status) values ($pci$epistemic-class$pci$, $pci$Epistemic class$pci$, $pci$The standing of a statement: DIRECT, SELF_REPORTED, INFERRED, PATTERN_SUPPORTED, INTERPRETIVE, SYMBOLIC, PHILOSOPHICAL, SPECULATIVE or UNKNOWN.$pci$, $pci$canonical$pci$, 'published') on conflict (slug) do nothing;
insert into public.glossary_terms (slug, term, definition, canon_status, status) values ($pci$epistemic-ledger$pci$, $pci$Epistemic Ledger$pci$, $pci$The section of an observational report that sorts findings into evidence, interpretation, inference, hypothesis, symbolic, philosophical and unknown.$pci$, $pci$derived$pci$, 'published') on conflict (slug) do nothing;
insert into public.glossary_terms (slug, term, definition, canon_status, status) values ($pci$confidence-calibration$pci$, $pci$Confidence calibration$pci$, $pci$Categorical confidence in place of fabricated numerical precision: High Support, Moderate Support, Limited Support, Insufficient Evidence, Undetermined.$pci$, $pci$canonical$pci$, 'published') on conflict (slug) do nothing;
insert into public.glossary_terms (slug, term, definition, canon_status, status) values ($pci$temporal-intelligence$pci$, $pci$Temporal intelligence$pci$, $pci$Careful classification of recurrence across time — isolated, repeated, emerging, historical, resurfacing, interrupted, transformed, and the surface / structural distinctions. Historical material is not presented as the present.$pci$, $pci$canonical$pci$, 'published') on conflict (slug) do nothing;
insert into public.glossary_terms (slug, term, definition, canon_status, status) values ($pci$context-differential$pci$, $pci$Context differential$pci$, $pci$For apparently similar observations: constants, changed conditions, context-sensitive features, context-invariant features, and missing comparison variables.$pci$, $pci$canonical$pci$, 'published') on conflict (slug) do nothing;
insert into public.glossary_terms (slug, term, definition, canon_status, status) values ($pci$contradiction$pci$, $pci$Contradiction$pci$, $pci$Tension between parts of the material, surfaced to be seen rather than to force one side to be false. Labelled only after comparing subject, meaning, scope, time, context and observer position.$pci$, $pci$canonical$pci$, 'published') on conflict (slug) do nothing;
insert into public.glossary_terms (slug, term, definition, canon_status, status) values ($pci$pattern-adoption$pci$, $pci$Pattern Adoption$pci$, $pci$An analytical sub-engine: Signal → Recurrence → Reinforcement → Defaulting → Integration → Identification → Preservation → Visibility → Revision. Not a personality label; it does not infer origin from recurrence alone.$pci$, $pci$canonical$pci$, 'published') on conflict (slug) do nothing;
insert into public.glossary_terms (slug, term, definition, canon_status, status) values ($pci$observer-observed$pci$, $pci$Observer / Observed$pci$, $pci$Distinguishing the observed event from observer position, attention, frames, expectation, meaning assignment, identity involvement, state and self-observation — without pathologizing the observer.$pci$, $pci$canonical$pci$, 'published') on conflict (slug) do nothing;
insert into public.glossary_terms (slug, term, definition, canon_status, status) values ($pci$meta-observational-integrity-audit$pci$, $pci$Meta-Observational Integrity Audit$pci$, $pci$One controlled self-audit before a report is finalised, checking inference inflation, interpretation leakage, lens contamination, identity inflation, narrative coherence bias, pattern overfitting, context collapse, confirmation loops, counter-hypotheses and disconfirming evidence.$pci$, $pci$canonical$pci$, 'published') on conflict (slug) do nothing;
insert into public.glossary_terms (slug, term, definition, canon_status, status) values ($pci$on-the-contrary$pci$, $pci$On the Contrary$pci$, $pci$A contained examination of an apparent error, imbalance, problem, unwanted event or contradiction within a wider relational system: Identified Error → Implied Expectation → Missing Variables → System Relationship → Contrary Position → Balance.$pci$, $pci$canonical$pci$, 'published') on conflict (slug) do nothing;
insert into public.glossary_terms (slug, term, definition, canon_status, status) values ($pci$balance$pci$, $pci$Balance$pci$, $pci$Relationship within a system. Balance does not automatically mean fairness, desirability, approval, justice, health, morality, correctness, comfort, or forced positivity.$pci$, $pci$canonical$pci$, 'published') on conflict (slug) do nothing;
insert into public.glossary_terms (slug, term, definition, canon_status, status) values ($pci$relational-intelligence$pci$, $pci$Relational intelligence$pci$, $pci$With explicit permission, comparing current material against previous material through traceable relationship types such as RELATED TO, CONTRADICTS, REPEATS and CHANGES UNDER.$pci$, $pci$canonical$pci$, 'published') on conflict (slug) do nothing;
insert into public.glossary_terms (slug, term, definition, canon_status, status) values ($pci$graph-edge$pci$, $pci$Graph edge$pci$, $pci$A recorded, visible relationship between two pieces of material. It is not automatically a causal mechanism.$pci$, $pci$canonical$pci$, 'published') on conflict (slug) do nothing;
insert into public.glossary_terms (slug, term, definition, canon_status, status) values ($pci$longitudinal-comparison$pci$, $pci$Longitudinal comparison$pci$, $pci$Comparison of current material with the user’s earlier material. Off unless the user explicitly enables it, and can be disabled at any time.$pci$, $pci$derived$pci$, 'published') on conflict (slug) do nothing;
insert into public.glossary_terms (slug, term, definition, canon_status, status) values ($pci$cognitive-twin$pci$, $pci$Cognitive Twin$pci$, $pci$An advanced, opt-in, revisable structural model generated from available material. Not a declaration of the user’s true self or essence; every element links to supporting and contradicting observations.$pci$, $pci$canonical$pci$, 'published') on conflict (slug) do nothing;
insert into public.glossary_terms (slug, term, definition, canon_status, status) values ($pci$causal-hypothesis$pci$, $pci$Causal hypothesis$pci$, $pci$Observed sequence → candidate mechanism → supporting evidence → alternative mechanism → disconfirming evidence → confidence. Sequence is not causation; causal relationships remain hypotheses unless independently demonstrated.$pci$, $pci$canonical$pci$, 'published') on conflict (slug) do nothing;
insert into public.glossary_terms (slug, term, definition, canon_status, status) values ($pci$self-correcting-theory$pci$, $pci$Self-correcting theory$pci$, $pci$Previous interpretation → new evidence → compatibility test → support / narrow / contradict / dissolve → new model version. Earlier versions are preserved.$pci$, $pci$canonical$pci$, 'published') on conflict (slug) do nothing;
insert into public.glossary_terms (slug, term, definition, canon_status, status) values ($pci$constitutional-invariant$pci$, $pci$Constitutional invariant$pci$, $pci$One of fifteen prohibited transformations — such as correlation → causation, behavior → permanent identity, or observation → prescription — enforced in contracts, schemas, validators, tests and report language.$pci$, $pci$canonical$pci$, 'published') on conflict (slug) do nothing;
insert into public.glossary_terms (slug, term, definition, canon_status, status) values ($pci$multi-lens-analysis$pci$, $pci$Multi-lens analysis$pci$, $pci$Optional analysis through separate lenses (cognitive, behavioral, systems, relational, identity, creative-process, Jungian, mythological, philosophical), each producing findings under its own label before comparison.$pci$, $pci$canonical$pci$, 'published') on conflict (slug) do nothing;
insert into public.glossary_terms (slug, term, definition, canon_status, status) values ($pci$lens-isolation$pci$, $pci$Lens isolation$pci$, $pci$Each lens keeps its findings, and their epistemic class, separate until cross-lens comparison. Symbolic resonance does not become empirical evidence.$pci$, $pci$canonical$pci$, 'published') on conflict (slug) do nothing;
insert into public.glossary_terms (slug, term, definition, canon_status, status) values ($pci$canon-status$pci$, $pci$Canon status$pci$, $pci$The standing of PCI content: canonical, derived, extended, provisional, external comparison, contradictory, or deprecated. Nothing is silently promoted from provisional to canonical.$pci$, $pci$canonical$pci$, 'published') on conflict (slug) do nothing;
insert into public.glossary_terms (slug, term, definition, canon_status, status) values ($pci$ledger$pci$, $pci$The Ledger$pci$, $pci$Unrestricted observational storage for observations, ideas, questions, quotes, contradictions, creative fragments, dreams, decisions, conversations, events, hypotheses and symbols.$pci$, $pci$canonical$pci$, 'published') on conflict (slug) do nothing;

insert into public.journal_prompts (id, ord, text, concept, canon_status, status) values ($pci$JP-001$pci$, 1, $pci$Out of the decisions you made today, which appeared to originate from the immediate situation, and which appeared to reproduce something familiar?$pci$, $pci$input$pci$, $pci$canonical$pci$, $pci$approved$pci$) on conflict (id) do nothing;
insert into public.journal_prompts (id, ord, text, concept, canon_status, status) values ($pci$JP-002$pci$, 2, $pci$What happened today that you are already explaining to yourself? Write only what occurred, before any explanation.$pci$, $pci$input$pci$, $pci$provisional$pci$, $pci$approved$pci$) on conflict (id) do nothing;
insert into public.journal_prompts (id, ord, text, concept, canon_status, status) values ($pci$JP-003$pci$, 3, $pci$Which moment today would a camera in the room have recorded differently from the way you remember it?$pci$, $pci$input$pci$, $pci$provisional$pci$, $pci$approved$pci$) on conflict (id) do nothing;
insert into public.journal_prompts (id, ord, text, concept, canon_status, status) values ($pci$JP-004$pci$, 4, $pci$What was said today, word for word, that stayed with you?$pci$, $pci$input$pci$, $pci$provisional$pci$, $pci$approved$pci$) on conflict (id) do nothing;
insert into public.journal_prompts (id, ord, text, concept, canon_status, status) values ($pci$JP-005$pci$, 5, $pci$Which event today arrived already labelled, as good or bad, before you had described it?$pci$, $pci$input$pci$, $pci$provisional$pci$, $pci$approved$pci$) on conflict (id) do nothing;
insert into public.journal_prompts (id, ord, text, concept, canon_status, status) values ($pci$JP-006$pci$, 6, $pci$What material is present for you today that has no event attached to it — a mood, an image, a thought?$pci$, $pci$input$pci$, $pci$provisional$pci$, $pci$approved$pci$) on conflict (id) do nothing;
insert into public.journal_prompts (id, ord, text, concept, canon_status, status) values ($pci$JP-007$pci$, 7, $pci$Describe one ordinary moment from today in as much plain detail as you can recall.$pci$, $pci$input$pci$, $pci$provisional$pci$, $pci$approved$pci$) on conflict (id) do nothing;
insert into public.journal_prompts (id, ord, text, concept, canon_status, status) values ($pci$JP-008$pci$, 8, $pci$What did you notice first when you woke, before the day had a story?$pci$, $pci$input$pci$, $pci$provisional$pci$, $pci$approved$pci$) on conflict (id) do nothing;
insert into public.journal_prompts (id, ord, text, concept, canon_status, status) values ($pci$JP-009$pci$, 9, $pci$In one situation from today, which part was the event, and which part was the meaning you gave it?$pci$, $pci$decomposition$pci$, $pci$provisional$pci$, $pci$approved$pci$) on conflict (id) do nothing;
insert into public.journal_prompts (id, ord, text, concept, canon_status, status) values ($pci$JP-010$pci$, 10, $pci$Which emotion appeared today, and what was it attached to when it appeared?$pci$, $pci$decomposition$pci$, $pci$provisional$pci$, $pci$approved$pci$) on conflict (id) do nothing;
insert into public.journal_prompts (id, ord, text, concept, canon_status, status) values ($pci$JP-011$pci$, 11, $pci$What judgment did you make today — of a person, a task or yourself — and what was it judged against?$pci$, $pci$decomposition$pci$, $pci$provisional$pci$, $pci$approved$pci$) on conflict (id) do nothing;
insert into public.journal_prompts (id, ord, text, concept, canon_status, status) values ($pci$JP-012$pci$, 12, $pci$What did you assume today without checking it?$pci$, $pci$decomposition$pci$, $pci$provisional$pci$, $pci$approved$pci$) on conflict (id) do nothing;
insert into public.journal_prompts (id, ord, text, concept, canon_status, status) values ($pci$JP-013$pci$, 13, $pci$What did you expect to happen today that did not, and where did that expectation come from in the moment?$pci$, $pci$decomposition$pci$, $pci$provisional$pci$, $pci$approved$pci$) on conflict (id) do nothing;
insert into public.journal_prompts (id, ord, text, concept, canon_status, status) values ($pci$JP-014$pci$, 14, $pci$Where today did “I did this” become “I am this”?$pci$, $pci$decomposition$pci$, $pci$provisional$pci$, $pci$approved$pci$) on conflict (id) do nothing;
insert into public.journal_prompts (id, ord, text, concept, canon_status, status) values ($pci$JP-015$pci$, 15, $pci$Which conditions today — tiredness, place, company, time — might have changed how something looked?$pci$, $pci$decomposition$pci$, $pci$provisional$pci$, $pci$approved$pci$) on conflict (id) do nothing;
insert into public.journal_prompts (id, ord, text, concept, canon_status, status) values ($pci$JP-016$pci$, 16, $pci$In a moment of friction today, what remains unknown to you about the other person’s side?$pci$, $pci$decomposition$pci$, $pci$provisional$pci$, $pci$approved$pci$) on conflict (id) do nothing;
insert into public.journal_prompts (id, ord, text, concept, canon_status, status) values ($pci$JP-017$pci$, 17, $pci$What did you do today, and what did you not do, in one situation that mattered to you?$pci$, $pci$decomposition$pci$, $pci$provisional$pci$, $pci$approved$pci$) on conflict (id) do nothing;
insert into public.journal_prompts (id, ord, text, concept, canon_status, status) values ($pci$JP-018$pci$, 18, $pci$Which feeling today described someone else’s conduct — “ignored”, “judged”, “let down” — rather than your own state?$pci$, $pci$decomposition$pci$, $pci$provisional$pci$, $pci$approved$pci$) on conflict (id) do nothing;
insert into public.journal_prompts (id, ord, text, concept, canon_status, status) values ($pci$JP-019$pci$, 19, $pci$Take one sentence you said or thought today. Which words in it are description, and which are evaluation?$pci$, $pci$decomposition$pci$, $pci$provisional$pci$, $pci$approved$pci$) on conflict (id) do nothing;
insert into public.journal_prompts (id, ord, text, concept, canon_status, status) values ($pci$JP-020$pci$, 20, $pci$What role were you in today (parent, colleague, friend, stranger), and how did the role shape what you saw?$pci$, $pci$decomposition$pci$, $pci$provisional$pci$, $pci$approved$pci$) on conflict (id) do nothing;
insert into public.journal_prompts (id, ord, text, concept, canon_status, status) values ($pci$JP-021$pci$, 21, $pci$Where has something structurally similar to today’s main event appeared before? What was different about the context then?$pci$, $pci$contextual_comparison$pci$, $pci$provisional$pci$, $pci$approved$pci$) on conflict (id) do nothing;
insert into public.journal_prompts (id, ord, text, concept, canon_status, status) values ($pci$JP-022$pci$, 22, $pci$What looked the same today as a previous time, yet took place under different conditions?$pci$, $pci$contextual_comparison$pci$, $pci$provisional$pci$, $pci$approved$pci$) on conflict (id) do nothing;
insert into public.journal_prompts (id, ord, text, concept, canon_status, status) values ($pci$JP-023$pci$, 23, $pci$Which of today’s reactions would have been different in another room, with other people, or at another hour?$pci$, $pci$contextual_comparison$pci$, $pci$provisional$pci$, $pci$approved$pci$) on conflict (id) do nothing;
insert into public.journal_prompts (id, ord, text, concept, canon_status, status) values ($pci$JP-024$pci$, 24, $pci$What stayed constant today across two quite different situations?$pci$, $pci$contextual_comparison$pci$, $pci$provisional$pci$, $pci$approved$pci$) on conflict (id) do nothing;
insert into public.journal_prompts (id, ord, text, concept, canon_status, status) values ($pci$JP-025$pci$, 25, $pci$Compare a morning moment with an evening moment from today. What changed besides the time?$pci$, $pci$contextual_comparison$pci$, $pci$provisional$pci$, $pci$approved$pci$) on conflict (id) do nothing;
insert into public.journal_prompts (id, ord, text, concept, canon_status, status) values ($pci$JP-026$pci$, 26, $pci$When did you last feel what you felt today? What was present then that is absent now?$pci$, $pci$contextual_comparison$pci$, $pci$provisional$pci$, $pci$approved$pci$) on conflict (id) do nothing;
insert into public.journal_prompts (id, ord, text, concept, canon_status, status) values ($pci$JP-027$pci$, 27, $pci$Which comparison did you make today between yourself and someone else, and what did the comparison leave out?$pci$, $pci$contextual_comparison$pci$, $pci$provisional$pci$, $pci$approved$pci$) on conflict (id) do nothing;
insert into public.journal_prompts (id, ord, text, concept, canon_status, status) values ($pci$JP-028$pci$, 28, $pci$What would today’s event look like if it had happened ten years ago?$pci$, $pci$contextual_comparison$pci$, $pci$provisional$pci$, $pci$approved$pci$) on conflict (id) do nothing;
insert into public.journal_prompts (id, ord, text, concept, canon_status, status) values ($pci$JP-029$pci$, 29, $pci$What appeared to repeat today, and under what conditions did it appear?$pci$, $pci$pattern_detection$pci$, $pci$provisional$pci$, $pci$approved$pci$) on conflict (id) do nothing;
insert into public.journal_prompts (id, ord, text, concept, canon_status, status) values ($pci$JP-030$pci$, 30, $pci$Which thought returned more than once today? What was happening each time it returned?$pci$, $pci$pattern_detection$pci$, $pci$provisional$pci$, $pci$approved$pci$) on conflict (id) do nothing;
insert into public.journal_prompts (id, ord, text, concept, canon_status, status) values ($pci$JP-031$pci$, 31, $pci$What do you describe with the word “always”? How many actual instances can you list?$pci$, $pci$pattern_detection$pci$, $pci$provisional$pci$, $pci$approved$pci$) on conflict (id) do nothing;
insert into public.journal_prompts (id, ord, text, concept, canon_status, status) values ($pci$JP-032$pci$, 32, $pci$Which response of yours seemed to arrive before you chose it today?$pci$, $pci$pattern_detection$pci$, $pci$provisional$pci$, $pci$approved$pci$) on conflict (id) do nothing;
insert into public.journal_prompts (id, ord, text, concept, canon_status, status) values ($pci$JP-033$pci$, 33, $pci$What repeated today in how others responded to you, and what was similar in how you approached them?$pci$, $pci$pattern_detection$pci$, $pci$provisional$pci$, $pci$approved$pci$) on conflict (id) do nothing;
insert into public.journal_prompts (id, ord, text, concept, canon_status, status) values ($pci$JP-034$pci$, 34, $pci$What did not repeat today that usually does? What was different?$pci$, $pci$pattern_detection$pci$, $pci$provisional$pci$, $pci$approved$pci$) on conflict (id) do nothing;
insert into public.journal_prompts (id, ord, text, concept, canon_status, status) values ($pci$JP-035$pci$, 35, $pci$Which small habit ran today without your attention? When did it become visible?$pci$, $pci$pattern_detection$pci$, $pci$provisional$pci$, $pci$approved$pci$) on conflict (id) do nothing;
insert into public.journal_prompts (id, ord, text, concept, canon_status, status) values ($pci$JP-036$pci$, 36, $pci$What is the most recent time something you call “a pattern” did not happen?$pci$, $pci$pattern_detection$pci$, $pci$provisional$pci$, $pci$approved$pci$) on conflict (id) do nothing;
insert into public.journal_prompts (id, ord, text, concept, canon_status, status) values ($pci$JP-037$pci$, 37, $pci$Where today did what you said and what you did point in different directions?$pci$, $pci$contradiction_detection$pci$, $pci$provisional$pci$, $pci$approved$pci$) on conflict (id) do nothing;
insert into public.journal_prompts (id, ord, text, concept, canon_status, status) values ($pci$JP-038$pci$, 38, $pci$What do you believe about yourself that today’s events did not match?$pci$, $pci$contradiction_detection$pci$, $pci$provisional$pci$, $pci$approved$pci$) on conflict (id) do nothing;
insert into public.journal_prompts (id, ord, text, concept, canon_status, status) values ($pci$JP-039$pci$, 39, $pci$What two things did you want today that could not both happen?$pci$, $pci$contradiction_detection$pci$, $pci$provisional$pci$, $pci$approved$pci$) on conflict (id) do nothing;
insert into public.journal_prompts (id, ord, text, concept, canon_status, status) values ($pci$JP-040$pci$, 40, $pci$Which opinion of yours shifted today, even slightly? What was the earlier version?$pci$, $pci$contradiction_detection$pci$, $pci$provisional$pci$, $pci$approved$pci$) on conflict (id) do nothing;
insert into public.journal_prompts (id, ord, text, concept, canon_status, status) values ($pci$JP-041$pci$, 41, $pci$Where did you say “I don’t mind” today while something in you did mind?$pci$, $pci$contradiction_detection$pci$, $pci$provisional$pci$, $pci$approved$pci$) on conflict (id) do nothing;
insert into public.journal_prompts (id, ord, text, concept, canon_status, status) values ($pci$JP-042$pci$, 42, $pci$What value did you hold today that was hard to act on? What happened instead?$pci$, $pci$contradiction_detection$pci$, $pci$provisional$pci$, $pci$approved$pci$) on conflict (id) do nothing;
insert into public.journal_prompts (id, ord, text, concept, canon_status, status) values ($pci$JP-043$pci$, 43, $pci$Which two accounts of the same event — yours and someone else’s — do not fit together?$pci$, $pci$contradiction_detection$pci$, $pci$provisional$pci$, $pci$approved$pci$) on conflict (id) do nothing;
insert into public.journal_prompts (id, ord, text, concept, canon_status, status) values ($pci$JP-044$pci$, 44, $pci$What tension from today remains unresolved, and what does it look like when left unresolved?$pci$, $pci$contradiction_detection$pci$, $pci$provisional$pci$, $pci$approved$pci$) on conflict (id) do nothing;
insert into public.journal_prompts (id, ord, text, concept, canon_status, status) values ($pci$JP-045$pci$, 45, $pci$What do you know happened today, and what do you believe happened?$pci$, $pci$evidentiary_separation$pci$, $pci$provisional$pci$, $pci$approved$pci$) on conflict (id) do nothing;
insert into public.journal_prompts (id, ord, text, concept, canon_status, status) values ($pci$JP-046$pci$, 46, $pci$Which conclusion from today rests on one moment alone?$pci$, $pci$evidentiary_separation$pci$, $pci$provisional$pci$, $pci$approved$pci$) on conflict (id) do nothing;
insert into public.journal_prompts (id, ord, text, concept, canon_status, status) values ($pci$JP-047$pci$, 47, $pci$What did you infer about someone’s intention today? What did they actually say or do?$pci$, $pci$evidentiary_separation$pci$, $pci$provisional$pci$, $pci$approved$pci$) on conflict (id) do nothing;
insert into public.journal_prompts (id, ord, text, concept, canon_status, status) values ($pci$JP-048$pci$, 48, $pci$What remains unknown about today’s main event, and how do you carry the unknown?$pci$, $pci$evidentiary_separation$pci$, $pci$provisional$pci$, $pci$approved$pci$) on conflict (id) do nothing;
insert into public.journal_prompts (id, ord, text, concept, canon_status, status) values ($pci$JP-049$pci$, 49, $pci$Which image or symbol stayed with you today? What is it, and what have you made it mean?$pci$, $pci$evidentiary_separation$pci$, $pci$provisional$pci$, $pci$approved$pci$) on conflict (id) do nothing;
insert into public.journal_prompts (id, ord, text, concept, canon_status, status) values ($pci$JP-050$pci$, 50, $pci$Which of today’s thoughts was a hypothesis that felt like a fact?$pci$, $pci$evidentiary_separation$pci$, $pci$provisional$pci$, $pci$approved$pci$) on conflict (id) do nothing;
insert into public.journal_prompts (id, ord, text, concept, canon_status, status) values ($pci$JP-051$pci$, 51, $pci$What did you report to yourself today about how you felt, and what else could the sensation have been?$pci$, $pci$evidentiary_separation$pci$, $pci$provisional$pci$, $pci$approved$pci$) on conflict (id) do nothing;
insert into public.journal_prompts (id, ord, text, concept, canon_status, status) values ($pci$JP-052$pci$, 52, $pci$If you had to mark today’s account with “seen”, “heard”, “felt” and “concluded”, where would each mark go?$pci$, $pci$evidentiary_separation$pci$, $pci$provisional$pci$, $pci$approved$pci$) on conflict (id) do nothing;
insert into public.journal_prompts (id, ord, text, concept, canon_status, status) values ($pci$JP-053$pci$, 53, $pci$After separating today’s material, what can simply be observed, without deciding what to do about it?$pci$, $pci$observational_report$pci$, $pci$provisional$pci$, $pci$approved$pci$) on conflict (id) do nothing;
insert into public.journal_prompts (id, ord, text, concept, canon_status, status) values ($pci$JP-054$pci$, 54, $pci$What became visible today that was not visible yesterday?$pci$, $pci$observational_report$pci$, $pci$provisional$pci$, $pci$approved$pci$) on conflict (id) do nothing;
insert into public.journal_prompts (id, ord, text, concept, canon_status, status) values ($pci$JP-055$pci$, 55, $pci$Describe today in five plain observations, none of which contains an instruction.$pci$, $pci$observational_report$pci$, $pci$provisional$pci$, $pci$approved$pci$) on conflict (id) do nothing;
insert into public.journal_prompts (id, ord, text, concept, canon_status, status) values ($pci$JP-056$pci$, 56, $pci$What is present in today’s material that does not need resolving tonight?$pci$, $pci$observational_report$pci$, $pci$provisional$pci$, $pci$approved$pci$) on conflict (id) do nothing;
insert into public.journal_prompts (id, ord, text, concept, canon_status, status) values ($pci$JP-057$pci$, 57, $pci$What would an account of today look like if it ended at observation?$pci$, $pci$observational_report$pci$, $pci$provisional$pci$, $pci$approved$pci$) on conflict (id) do nothing;
insert into public.journal_prompts (id, ord, text, concept, canon_status, status) values ($pci$JP-058$pci$, 58, $pci$What did you notice yourself noticing today?$pci$, $pci$observer_observed$pci$, $pci$provisional$pci$, $pci$approved$pci$) on conflict (id) do nothing;
insert into public.journal_prompts (id, ord, text, concept, canon_status, status) values ($pci$JP-059$pci$, 59, $pci$Where was your attention today, and what did it pass over?$pci$, $pci$observer_observed$pci$, $pci$provisional$pci$, $pci$approved$pci$) on conflict (id) do nothing;
insert into public.journal_prompts (id, ord, text, concept, canon_status, status) values ($pci$JP-060$pci$, 60, $pci$What frame were you looking through when today’s strongest moment happened?$pci$, $pci$observer_observed$pci$, $pci$provisional$pci$, $pci$approved$pci$) on conflict (id) do nothing;
insert into public.journal_prompts (id, ord, text, concept, canon_status, status) values ($pci$JP-061$pci$, 61, $pci$How did your state — rested, hurried, hungry, calm — shape what you perceived today?$pci$, $pci$observer_observed$pci$, $pci$provisional$pci$, $pci$approved$pci$) on conflict (id) do nothing;
insert into public.journal_prompts (id, ord, text, concept, canon_status, status) values ($pci$JP-062$pci$, 62, $pci$When did you watch yourself today as if from the outside? What did you see?$pci$, $pci$observer_observed$pci$, $pci$provisional$pci$, $pci$approved$pci$) on conflict (id) do nothing;
insert into public.journal_prompts (id, ord, text, concept, canon_status, status) values ($pci$JP-063$pci$, 63, $pci$Which of today’s judgments says more about the one judging than the one judged?$pci$, $pci$observer_observed$pci$, $pci$provisional$pci$, $pci$approved$pci$) on conflict (id) do nothing;
insert into public.journal_prompts (id, ord, text, concept, canon_status, status) values ($pci$JP-064$pci$, 64, $pci$What meaning did you assign today within a second of seeing something?$pci$, $pci$observer_observed$pci$, $pci$provisional$pci$, $pci$approved$pci$) on conflict (id) do nothing;
insert into public.journal_prompts (id, ord, text, concept, canon_status, status) values ($pci$JP-065$pci$, 65, $pci$What happened to an observation today once you became part of it?$pci$, $pci$observer_observed$pci$, $pci$provisional$pci$, $pci$approved$pci$) on conflict (id) do nothing;
insert into public.journal_prompts (id, ord, text, concept, canon_status, status) values ($pci$JP-066$pci$, 66, $pci$Which way of responding did you use today that you remember first using long ago?$pci$, $pci$pattern_adoption$pci$, $pci$provisional$pci$, $pci$approved$pci$) on conflict (id) do nothing;
insert into public.journal_prompts (id, ord, text, concept, canon_status, status) values ($pci$JP-067$pci$, 67, $pci$What habit of thought was reinforced today, and by what?$pci$, $pci$pattern_adoption$pci$, $pci$provisional$pci$, $pci$approved$pci$) on conflict (id) do nothing;
insert into public.journal_prompts (id, ord, text, concept, canon_status, status) values ($pci$JP-068$pci$, 68, $pci$What do you do by default in conflict? When did the default run today?$pci$, $pci$pattern_adoption$pci$, $pci$provisional$pci$, $pci$approved$pci$) on conflict (id) do nothing;
insert into public.journal_prompts (id, ord, text, concept, canon_status, status) values ($pci$JP-069$pci$, 69, $pci$Which pattern have you begun to call part of who you are? When is it absent?$pci$, $pci$pattern_adoption$pci$, $pci$provisional$pci$, $pci$approved$pci$) on conflict (id) do nothing;
insert into public.journal_prompts (id, ord, text, concept, canon_status, status) values ($pci$JP-070$pci$, 70, $pci$What pattern became visible to you today while it was happening?$pci$, $pci$pattern_adoption$pci$, $pci$provisional$pci$, $pci$approved$pci$) on conflict (id) do nothing;
insert into public.journal_prompts (id, ord, text, concept, canon_status, status) values ($pci$JP-071$pci$, 71, $pci$What pattern has changed in you over the last year, and under what conditions does the older version still appear?$pci$, $pci$pattern_adoption$pci$, $pci$provisional$pci$, $pci$approved$pci$) on conflict (id) do nothing;
insert into public.journal_prompts (id, ord, text, concept, canon_status, status) values ($pci$JP-072$pci$, 72, $pci$What went wrong today? What expectation made it wrong?$pci$, $pci$on_the_contrary$pci$, $pci$provisional$pci$, $pci$approved$pci$) on conflict (id) do nothing;
insert into public.journal_prompts (id, ord, text, concept, canon_status, status) values ($pci$JP-073$pci$, 73, $pci$Which problem from today would look different from another position within the same situation?$pci$, $pci$on_the_contrary$pci$, $pci$provisional$pci$, $pci$approved$pci$) on conflict (id) do nothing;
insert into public.journal_prompts (id, ord, text, concept, canon_status, status) values ($pci$JP-074$pci$, 74, $pci$What variables were missing from your view of today’s unwanted event?$pci$, $pci$on_the_contrary$pci$, $pci$provisional$pci$, $pci$approved$pci$) on conflict (id) do nothing;
insert into public.journal_prompts (id, ord, text, concept, canon_status, status) values ($pci$JP-075$pci$, 75, $pci$Within what larger system did today’s difficulty take place? Who and what else was part of it?$pci$, $pci$on_the_contrary$pci$, $pci$provisional$pci$, $pci$approved$pci$) on conflict (id) do nothing;
insert into public.journal_prompts (id, ord, text, concept, canon_status, status) values ($pci$JP-076$pci$, 76, $pci$What did today’s imbalance make visible about the relationship between the parts?$pci$, $pci$on_the_contrary$pci$, $pci$provisional$pci$, $pci$approved$pci$) on conflict (id) do nothing;
insert into public.journal_prompts (id, ord, text, concept, canon_status, status) values ($pci$JP-077$pci$, 77, $pci$What is the contrary position to your strongest reaction today, stated as its holder would state it?$pci$, $pci$on_the_contrary$pci$, $pci$provisional$pci$, $pci$approved$pci$) on conflict (id) do nothing;
insert into public.journal_prompts (id, ord, text, concept, canon_status, status) values ($pci$JP-078$pci$, 78, $pci$What did you repeat today that was not quite the same as last time? What had changed — in you, the context, or the act?$pci$, $pci$repetition$pci$, $pci$provisional$pci$, $pci$approved$pci$) on conflict (id) do nothing;
insert into public.journal_prompts (id, ord, text, concept, canon_status, status) values ($pci$JP-079$pci$, 79, $pci$Which practice did you do today? What did the repetition feel like this time?$pci$, $pci$repetition$pci$, $pci$provisional$pci$, $pci$approved$pci$) on conflict (id) do nothing;
insert into public.journal_prompts (id, ord, text, concept, canon_status, status) values ($pci$JP-080$pci$, 80, $pci$Where did you expect today to be a copy of yesterday, and where was it not?$pci$, $pci$repetition$pci$, $pci$provisional$pci$, $pci$approved$pci$) on conflict (id) do nothing;
insert into public.journal_prompts (id, ord, text, concept, canon_status, status) values ($pci$JP-081$pci$, 81, $pci$Was there a moment today with no strong reaction? What was present in it?$pci$, $pci$neutrality$pci$, $pci$provisional$pci$, $pci$approved$pci$) on conflict (id) do nothing;
insert into public.journal_prompts (id, ord, text, concept, canon_status, status) values ($pci$JP-082$pci$, 82, $pci$What subtle thing did you perceive today that a louder moment would have covered?$pci$, $pci$neutrality$pci$, $pci$provisional$pci$, $pci$approved$pci$) on conflict (id) do nothing;
insert into public.journal_prompts (id, ord, text, concept, canon_status, status) values ($pci$JP-083$pci$, 83, $pci$Which event today did you manage to see before deciding how you felt about it?$pci$, $pci$neutrality$pci$, $pci$provisional$pci$, $pci$approved$pci$) on conflict (id) do nothing;
insert into public.journal_prompts (id, ord, text, concept, canon_status, status) values ($pci$JP-084$pci$, 84, $pci$Which emotion today carried information? What was it pointing at?$pci$, $pci$emotion$pci$, $pci$provisional$pci$, $pci$approved$pci$) on conflict (id) do nothing;
insert into public.journal_prompts (id, ord, text, concept, canon_status, status) values ($pci$JP-085$pci$, 85, $pci$Which emotion did you have today without it having you?$pci$, $pci$emotion$pci$, $pci$provisional$pci$, $pci$approved$pci$) on conflict (id) do nothing;
insert into public.journal_prompts (id, ord, text, concept, canon_status, status) values ($pci$JP-086$pci$, 86, $pci$Which feeling today did you call a problem? What was it before it was called that?$pci$, $pci$emotion$pci$, $pci$provisional$pci$, $pci$approved$pci$) on conflict (id) do nothing;
insert into public.journal_prompts (id, ord, text, concept, canon_status, status) values ($pci$JP-087$pci$, 87, $pci$Which version of yourself appeared today that you do not usually include in your self-description?$pci$, $pci$identity$pci$, $pci$provisional$pci$, $pci$approved$pci$) on conflict (id) do nothing;
insert into public.journal_prompts (id, ord, text, concept, canon_status, status) values ($pci$JP-088$pci$, 88, $pci$What possibility showed up in you today that does not fit the identity you usually hold?$pci$, $pci$identity$pci$, $pci$provisional$pci$, $pci$approved$pci$) on conflict (id) do nothing;
insert into public.journal_prompts (id, ord, text, concept, canon_status, status) values ($pci$JP-089$pci$, 89, $pci$Where today did a choice happen without being noticed as a choice?$pci$, $pci$choice$pci$, $pci$provisional$pci$, $pci$approved$pci$) on conflict (id) do nothing;
insert into public.journal_prompts (id, ord, text, concept, canon_status, status) values ($pci$JP-090$pci$, 90, $pci$Which choice from today is still open, and what does it look like from here?$pci$, $pci$choice$pci$, $pci$provisional$pci$, $pci$approved$pci$) on conflict (id) do nothing;

insert into public.courses (slug, title, summary, canon_status, status) values ($pci$pci-foundations$pci$, $pci$PCI Foundations: The Seven Operations$pci$, $pci$A guided route through the seven principles / operations, the STOP boundary and the epistemic classes, using the canonical PCI framework texts. Each lesson ends with an observation and a journal subject; analysis is optional.$pci$, $pci$derived$pci$, $pci$published$pci$) on conflict (slug) do nothing;
insert into public.course_modules (course_slug, slug, title, ord) values ($pci$pci-foundations$pci$, $pci$orientation$pci$, $pci$Orientation$pci$, 1) on conflict do nothing;
insert into public.course_modules (course_slug, slug, title, ord) values ($pci$pci-foundations$pci$, $pci$separating$pci$, $pci$Separating the material$pci$, 2) on conflict do nothing;
insert into public.course_modules (course_slug, slug, title, ord) values ($pci$pci-foundations$pci$, $pci$relating$pci$, $pci$Relating the material$pci$, 3) on conflict do nothing;
insert into public.course_modules (course_slug, slug, title, ord) values ($pci$pci-foundations$pci$, $pci$reporting$pci$, $pci$Reporting and stopping$pci$, 4) on conflict do nothing;
insert into public.lessons (course_slug, lesson_id, module_slug, ord, title, video_url, transcript, related_chapters, related_concepts, journal_prompt, optional_observation, resources)
values ($pci$pci-foundations$pci$, $pci$the-boundary$pci$, $pci$orientation$pci$, 1, $pci$Visibility, and where it stops$pci$, null, null, array[]::text[], array[$pci$pci$pci$, $pci$visibility$pci$, $pci$stop-boundary$pci$]::text[], $pci$Where today did an observation of yours turn, within a sentence, into an instruction?$pci$, true, $pci$[]$pci$::jsonb)
on conflict do nothing;
insert into public.lessons (course_slug, lesson_id, module_slug, ord, title, video_url, transcript, related_chapters, related_concepts, journal_prompt, optional_observation, resources)
values ($pci$pci-foundations$pci$, $pci$input$pci$, $pci$separating$pci$, 2, $pci$Input: before explanation$pci$, null, null, array[]::text[], array[$pci$input$pci$, $pci$structured-observation-record$pci$]::text[], $pci$What happened today that you are already explaining to yourself? Write only what occurred, before any explanation.$pci$, true, $pci$[]$pci$::jsonb)
on conflict do nothing;
insert into public.lessons (course_slug, lesson_id, module_slug, ord, title, video_url, transcript, related_chapters, related_concepts, journal_prompt, optional_observation, resources)
values ($pci$pci-foundations$pci$, $pci$decomposition$pci$, $pci$separating$pci$, 3, $pci$Decomposition: one narrative, many parts$pci$, null, null, array[]::text[], array[$pci$decomposition$pci$, $pci$interpretation$pci$, $pci$identity-attribution$pci$]::text[], $pci$In one situation from today, which part was the event, and which part was the meaning you gave it?$pci$, true, $pci$[]$pci$::jsonb)
on conflict do nothing;
insert into public.lessons (course_slug, lesson_id, module_slug, ord, title, video_url, transcript, related_chapters, related_concepts, journal_prompt, optional_observation, resources)
values ($pci$pci-foundations$pci$, $pci$evidentiary-separation$pci$, $pci$separating$pci$, 4, $pci$Evidentiary Separation$pci$, null, null, array[]::text[], array[$pci$epistemic-class$pci$, $pci$confidence-calibration$pci$]::text[], $pci$What do you know happened today, and what do you believe happened?$pci$, true, $pci$[]$pci$::jsonb)
on conflict do nothing;
insert into public.lessons (course_slug, lesson_id, module_slug, ord, title, video_url, transcript, related_chapters, related_concepts, journal_prompt, optional_observation, resources)
values ($pci$pci-foundations$pci$, $pci$contextual-comparison$pci$, $pci$relating$pci$, 5, $pci$Contextual Comparison$pci$, null, null, array[]::text[], array[$pci$contextual-comparison$pci$, $pci$context-differential$pci$, $pci$temporal-intelligence$pci$]::text[], $pci$Where has something structurally similar to today’s main event appeared before? What was different about the context then?$pci$, true, $pci$[]$pci$::jsonb)
on conflict do nothing;
insert into public.lessons (course_slug, lesson_id, module_slug, ord, title, video_url, transcript, related_chapters, related_concepts, journal_prompt, optional_observation, resources)
values ($pci$pci-foundations$pci$, $pci$pattern-detection$pci$, $pci$relating$pci$, 6, $pci$Pattern Detection and Pattern Adoption$pci$, null, null, array[]::text[], array[$pci$pattern-detection$pci$, $pci$pattern-adoption$pci$]::text[], $pci$What appeared to repeat today, and under what conditions did it appear?$pci$, true, $pci$[]$pci$::jsonb)
on conflict do nothing;
insert into public.lessons (course_slug, lesson_id, module_slug, ord, title, video_url, transcript, related_chapters, related_concepts, journal_prompt, optional_observation, resources)
values ($pci$pci-foundations$pci$, $pci$contradiction-detection$pci$, $pci$relating$pci$, 7, $pci$Contradiction Detection$pci$, null, null, array[]::text[], array[$pci$contradiction$pci$, $pci$contradiction-detection$pci$]::text[], $pci$Where today did what you said and what you did point in different directions?$pci$, true, $pci$[]$pci$::jsonb)
on conflict do nothing;
insert into public.lessons (course_slug, lesson_id, module_slug, ord, title, video_url, transcript, related_chapters, related_concepts, journal_prompt, optional_observation, resources)
values ($pci$pci-foundations$pci$, $pci$observational-report$pci$, $pci$reporting$pci$, 8, $pci$The Observational Report$pci$, null, null, array[]::text[], array[$pci$observational-report$pci$, $pci$meta-observational-integrity-audit$pci$]::text[], $pci$After separating today’s material, what can simply be observed, without deciding what to do about it?$pci$, true, $pci$[]$pci$::jsonb)
on conflict do nothing;

insert into public.courses (slug, title, summary, canon_status, status) values ($pci$art-of-being-foundations$pci$, $pci$The Art of Being — Foundations$pci$, $pci$Module → Short Video → Reading → Observation → Journal → Optional PCI Analysis, built on The Art of Being. Awaiting the approved manuscript and video material.$pci$, $pci$provisional$pci$, $pci$draft$pci$) on conflict (slug) do nothing;

commit;
