import { expect, test } from '@playwright/test'
import { onboard } from './helpers'

test.describe('Library and reader (R2)', () => {
  test('shows only complete texts: the book and companion articles are listed, unsupplied matter is not', async ({ page }) => {
    await page.goto('library/')
    await expect(page.getByRole('link', { name: /The Seven Principles \/ Operations/ })).toBeVisible()
    await expect(page.getByRole('link', { name: 'Repetition Is Not Repetition' })).toBeVisible()
    await expect(page.getByRole('link', { name: /The AAA Method/ })).toBeVisible()
    await expect(page.getByRole('link', { name: 'Appendix' })).toHaveCount(0)
    await page.goto('library/art-of-being/chapter-03/')
    await expect(page.getByRole('heading', { level: 1, name: 'You Were Finished at Birth' })).toBeVisible()
    await expect(page.getByText('The Art of Being · Chapter 3')).toBeVisible()
    await expect(page.getByRole('heading', { level: 2, name: 'The Economy of Insufficiency' })).toBeVisible()
    await page.goto('library/the-aaa-method/')
    await expect(page.getByText('PCI Companion Article', { exact: true })).toBeVisible()
    await page.goto('library/art-of-being/appendix/')
    await expect(page.getByText(/This text is not published/)).toBeVisible()
  })

  test('reader: glossary definition, bookmark, note, previous/next', async ({ page }) => {
    await onboard(page)
    await page.goto('library/what-pci-is/')
    await page.getByRole('button', { name: 'Psycho-Creative Intelligence' }).click()
    await expect(page.getByRole('tooltip')).toContainText('observational intelligence environment')
    await page.keyboard.press('Escape')
    await expect(page.getByRole('tooltip')).toHaveCount(0)
    const block = page.locator('#b-1')
    await block.hover()
    await block.getByRole('button', { name: 'Bookmark this passage' }).click()
    await expect(block.getByLabel('Bookmarked')).toBeVisible()
    await block.getByRole('button', { name: 'Add a note' }).click()
    await page.getByLabel('Note', { exact: true }).fill('Structure, not obligation.')
    await page.getByRole('button', { name: 'Save note' }).click()
    await expect(page.getByText('Structure, not obligation.')).toBeVisible()
    await page.getByRole('link', { name: /Next The Seven Principles/ }).click()
    await expect(page.getByRole('heading', { level: 1, name: 'The Seven Principles / Operations' })).toBeVisible()
    await page.goto('today/')
    await expect(page.getByRole('link', { name: 'What PCI Is — and What It Is Not' })).toBeVisible()
  })

  test('glossary and search label public vs private results', async ({ page }) => {
    await onboard(page)
    await page.goto('reflection/')
    await page.getByLabel('Journal entry').fill('A private thought about balance at work.')
    await expect(page.getByText('Saved', { exact: true })).toBeVisible()
    await page.goto('search/?q=balance')
    await expect(page.getByText(/PCI content · /).first()).toBeVisible()
    await expect(page.getByText(/Private · Journal/)).toBeVisible()
    await page.goto('library/glossary/')
    await expect(page.locator('#balance')).toContainText('does not automatically mean fairness')
  })

  test('CMS: a chapter cannot publish without its full text, and can once complete', async ({ page }) => {
    await onboard(page)
    await page.goto('admin/edit/?slug=appendix')
    await expect(page.getByText(/title without a body cannot be published/)).toBeVisible()
    await page.getByRole('button', { name: 'Move to Review' }).click()
    await page.getByRole('button', { name: 'Move to Approved' }).click()
    await expect(page.getByRole('button', { name: 'Move to Published' })).toBeDisabled()
    await page.getByRole('button', { name: 'Move to Review' }).click()
    await page.getByRole('button', { name: 'Return to draft' }).click()
    await page.getByLabel('Body').fill('Being is Manifested; Becoming is Manufactured. '.repeat(12))
    await page.getByLabel('Change note').fill('Manuscript entered for preview')
    await page.getByRole('button', { name: 'Save draft' }).click()
    await page.getByRole('button', { name: 'Move to Review' }).click()
    await page.getByRole('button', { name: 'Move to Approved' }).click()
    await page.getByRole('button', { name: 'Move to Published' }).click()
    await expect(page.getByText('Moved to Published.')).toBeVisible()
    await page.goto('library/art-of-being/appendix/')
    await expect(page.getByRole('heading', { level: 1, name: 'Appendix' })).toBeVisible()
  })
})

test.describe('Ledger (R2)', () => {
  test('keeps entries of any kind, links them, and archives', async ({ page }) => {
    await onboard(page)
    await page.goto('ledger/')
    await page.getByLabel('Kind', { exact: true }).selectOption('dream')
    await page.getByLabel('Title (optional)').fill('The house with no doors')
    await page.getByLabel('Entry', { exact: true }).fill('I dreamt of a house with no doors, and I was calm inside it.')
    await page.getByRole('button', { name: 'Keep' }).click()
    await page.getByRole('link', { name: /The house with no doors/ }).click()
    await page.getByRole('button', { name: 'Archive' }).click()
    await expect(page.getByText('Archived', { exact: true })).toBeVisible()
    await page.getByRole('button', { name: 'Analyse through PCI' }).click()
    await expect(page).toHaveURL(/report/)
    await expect(page.locator('#visible').getByText(/held as symbol, not as fact/)).toBeVisible()
  })
})

test.describe('On the Contrary (R3)', () => {
  test('six steps save and resume; balance is not approval; harm stays named', async ({ page }) => {
    await onboard(page)
    await page.goto('contrary/')
    await page.getByRole('button', { name: 'Begin a session' }).click()
    await expect(page).toHaveURL(/contrary\/session/)
    await page.getByLabel('Session title').fill('The shouting')
    await page.getByRole('textbox', { name: 'Identified Error' }).fill('He shouted at me and threatened me in front of the team. It should never have happened.')
    await expect(page.getByText(/Harm named in this material remains harm/)).toBeVisible()
    await page.getByRole('button', { name: 'Next step' }).click()
    await expect(page.getByText(/Expectation language in the identified error/)).toBeVisible()
    await page.getByRole('textbox', { name: 'Implied Expectation' }).fill('I expected to be spoken to with respect.')
    await expect(page.getByText('Saved', { exact: true })).toBeVisible()
    await page.goto('contrary/')
    await expect(page.getByText('Step 2 of 6')).toBeVisible()
    await page.getByRole('link', { name: /The shouting/ }).click()
    await expect(page.getByRole('textbox', { name: 'Implied Expectation' })).toHaveValue('I expected to be spoken to with respect.')
    await page.getByRole('button', { name: /6\s*Balance/ }).click()
    await expect(page.getByText(/does not automatically mean fairness/).first()).toBeVisible()
    const text = await page.locator('main').innerText()
    expect(text).not.toMatch(/happened for a reason|silver lining|blessing in disguise/i)
  })
})

test.describe('Academy (R3)', () => {
  test('a lesson reuses the Library, saves the journal, and records informational progress', async ({ page }) => {
    await onboard(page)
    await page.goto('academy/pci-foundations/')
    await page.getByRole('link', { name: 'Begin' }).click()
    await expect(page.getByRole('heading', { level: 1, name: 'Visibility, and where it stops' })).toBeVisible()
    await expect(page.getByRole('link', { name: /What PCI Is — and What It Is Not/ })).toBeVisible()
    await page.getByLabel('Lesson journal').fill('A friend told me to quit. She observed that I was tired.')
    await expect(page.getByText('Saved', { exact: true })).toBeVisible()
    await page.getByRole('button', { name: 'Mark lesson complete' }).click()
    await expect(page.getByRole('button', { name: 'Completed' })).toBeDisabled()
    await page.goto('academy/pci-foundations/')
    await expect(page.getByText('Completed').first()).toBeVisible()
    await page.goto('reflection/archive/')
    await expect(page.getByText(/A friend told me to quit/)).toBeVisible()
  })
})

test.describe('Relational intelligence (R4) and Cognitive Twin (R6)', () => {
  test('is gated behind explicit permission', async ({ page }) => {
    await onboard(page)
    await page.goto('relate/')
    await expect(page.getByText('Comparison with earlier material is off')).toBeVisible()
    await page.getByRole('switch', { name: /earlier material/ }).click()
    await expect(page.getByText(/visible relationships/)).toBeVisible()
  })

  test('maps relationships across material and withholds the twin without enough history', async ({ page }) => {
    await onboard(page, { longitudinal: true })
    for (const body of ['The deadline at work made me anxious again.', 'Another deadline at work, anxious all day.', 'The deadline moved; I love my job but I felt anxious.', 'I hate my job some days.']) {
      await page.goto('ledger/')
      await page.getByLabel('Entry', { exact: true }).fill(body)
      await page.getByRole('button', { name: 'Keep' }).click()
      await expect(page.getByText(body)).toBeVisible()
    }
    await page.goto('relate/')
    await expect(page.getByRole('img', { name: /Timeline of your material/ })).toBeVisible()
    await page.getByRole('tab', { name: /Patterns/ }).click()
    await expect(page.getByText('“deadline”')).toBeVisible()
    await page.getByRole('tab', { name: /Contradictions/ }).click()
    await expect(page.getByText('love / hate')).toBeVisible()
    await page.getByRole('tab', { name: /Cognitive Twin/ }).click()
    await page.getByRole('switch', { name: 'Enable the Cognitive Twin' }).click()
    await expect(page.getByText('Not enough longitudinal material yet')).toBeVisible()
  })
})
