import { expect, test } from '@playwright/test'
import { enter } from './helpers'

test.describe('Library and reader (R2)', () => {
  test('shows only complete texts: the book and companion articles are listed, unsupplied matter is not', async ({ page }) => {
    await page.goto('library/')
    // Framework texts transcribed from the blueprint are not live handoff content and stay unpublished.
    await expect(page.getByRole('link', { name: /The Seven Principles/ })).toHaveCount(0)
    await expect(page.getByRole('link', { name: /Repetition Is Not Repetition/ })).toBeVisible()
    await expect(page.getByRole('link', { name: /The AAA Method/ })).toBeVisible()
    await expect(page.getByRole('link', { name: 'Appendix' })).toHaveCount(0)
    await page.goto('library/art-of-being/chapter-03/')
    await expect(page.getByRole('heading', { level: 1, name: 'You Were Finished at Birth' })).toBeVisible()
    await expect(page.getByText('The Art of Being · Chapter 3')).toBeVisible()
    await expect(page.getByRole('heading', { level: 2, name: 'The Economy of Insufficiency' })).toBeVisible()
    await page.goto('library/the-aaa-method/')
    await expect(page.getByText(/Companion article/i).first()).toBeVisible()
    await page.goto('library/art-of-being/appendix/')
    await expect(page.getByText(/This text is not published/)).toBeVisible()
  })

  test('reader: bookmark, note, previous/next, and the ending line', async ({ page }) => {
    await enter(page)
    await page.goto('library/art-of-being/chapter-01/')
    await expect(page.getByText('This text may be read. It is not a duty.')).toBeVisible()
    const block = page.locator('#b-1')
    await block.hover()
    await block.getByRole('button', { name: 'Bookmark this passage' }).click()
    await expect(block.getByLabel('Bookmarked')).toBeVisible()
    await block.getByRole('button', { name: 'Add a note' }).click()
    await page.getByLabel('Note', { exact: true }).fill('Structure, not obligation.')
    await page.getByRole('button', { name: 'Save note' }).click()
    await expect(page.getByText('Structure, not obligation.')).toBeVisible()
    await page.getByRole('link', { name: /Next.*Practice as a Mythology/ }).click()
    await expect(page.getByRole('heading', { level: 1, name: 'Practice as a Mythology' })).toBeVisible()
  })

  test('glossary defines terms in place', async ({ page }) => {
    await page.goto('library/glossary/')
    await expect(page.locator('#balance')).toContainText('does not automatically mean fairness')
  })

  test('CMS: a chapter cannot publish without its full text, and can once complete', async ({ page }) => {
    await enter(page)
    await page.goto('admin/edit/?slug=appendix')
    await expect(page.getByText(/title without a body cannot be published/)).toBeVisible()
    await page.getByRole('button', { name: 'Move to Review' }).click()
    await page.getByRole('button', { name: 'Move to Approved' }).click()
    await expect(page.getByRole('button', { name: 'Move to Published' })).toBeDisabled()
    await page.getByRole('button', { name: 'Move to Review' }).click()
    await page.getByRole('button', { name: 'Return to draft' }).click()
    await page.getByLabel('Body').fill('Being is Manifested; Becoming is Manufactured. '.repeat(12))
    await page.getByLabel('Change note').fill('Manuscript entered for preview')
    await page.getByRole('button', { name: 'Save draft' }).click()
    await page.getByRole('button', { name: 'Move to Review' }).click()
    await page.getByRole('button', { name: 'Move to Approved' }).click()
    await page.getByRole('button', { name: 'Move to Published' }).click()
    await expect(page.getByText('Moved to Published.')).toBeVisible()
    await page.goto('library/art-of-being/appendix/')
    await expect(page.getByRole('heading', { level: 1, name: 'Appendix' })).toBeVisible()
  })
})

test.describe('On the Contrary (R3)', () => {
  test('six steps save and resume; balance is not approval; harm stays named', async ({ page }) => {
    await enter(page)
    await page.goto('contrary/')
    await page.getByRole('button', { name: 'Begin a session' }).click()
    await expect(page).toHaveURL(/contrary\/session/)
    await page.getByLabel('Session title').fill('The shouting')
    await page.getByRole('textbox', { name: 'Identified Error' }).fill('He shouted at me and threatened me in front of the team. It should never have happened.')
    await expect(page.getByText(/Harm named in this material remains harm/)).toBeVisible()
    await page.getByRole('button', { name: 'Next step' }).click()
    await expect(page.getByText(/Expectation language in the identified error/)).toBeVisible()
    await page.getByRole('textbox', { name: 'Implied Expectation' }).fill('I expected to be spoken to with respect.')
    await expect(page.getByText('Saved', { exact: true })).toBeVisible()
    await page.goto('contrary/')
    await expect(page.getByText('Step 2 of 6')).toBeVisible()
    await page.getByRole('link', { name: /The shouting/ }).click()
    await expect(page.getByRole('textbox', { name: 'Implied Expectation' })).toHaveValue('I expected to be spoken to with respect.')
    await page.getByRole('button', { name: /6\s*Balance/ }).click()
    await expect(page.getByText(/does not automatically mean fairness/).first()).toBeVisible()
    const text = await page.locator('main').innerText()
    expect(text).not.toMatch(/happened for a reason|silver lining|blessing in disguise/i)
  })
})
